### ISSUE TITLE
Async _fetch_certs does not decode certs - TypeError Object of type bytes is not JSON serializable

### ISSUE THREAD

**Issue by lawrencealexander10** [googleapis/google-auth-library-python#1050]
https://github.com/googleapis/google-auth-library-python/blob/7da6cfcbd1b3b94e63ec85b5a4382d32eadba52d/google/oauth2/_id_token_async.py#L98

There is a bug in the code. The json.dumps returns a `TypeError: Object of type bytes is not JSON serializable` while data instead needs to be decoded `data.decode('utf-8')` before converting to dictionary.

The correct approach is being used in the id_token.py method.

**Comment by sai-sunder-s** [comment]
Thank you for raising this issue. We will fix the bug.
