### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [googleapis/google-auth-library-python#1055]
Could you please consider to utilize unittest.mock instead of mock?

`s/import mock/from unittest import mock/`

should suffice.

**Comment by sai-sunder-s** [comment]
google-auth library supports older versions of python as well. So we are still using the backport of unittest.mock.

Please feel free to reopen the issue if this doesn't answer your question.

**Comment by dvzrv** [comment]
Hi! :wave: 

We are trying to remove python-mock from the Arch Linux repositories finally. This project is unfortunately blocking us from doing so.

**Comment by dvzrv** [comment]
This project only supports Python >= 3.7 so using unittest.mock should be the norm, as it has been included in Python since 3.3

**Comment by musicinmybrain** [comment]
See also https://github.com/googleapis/google-auth-library-python/pull/1786, https://github.com/googleapis/google-auth-library-python/pull/1361.
