### ISSUE TITLE
Google API Authentication

### ISSUE THREAD

**Issue by 0vally1** [googleapis/google-auth-library-python#1058]
Scenario: Many accounts are registered on Google Cloud Platform, there are many company projects, and the API monitoring interface is accessed.

Question: The .json file downloaded from Google Cloud has many accounts because there are many accounts and many projects, but the API accessed is the same interface, how do I set it in the environment variables of the machine, I see you write fixed parameters in the code，I saw the basic code package, and even wrote fixed parameters, such as  CREDENTIALS = "GOOGLE_APPLICATION_CREDENTIALS"

What should I do, to modify it so that it does not read the environment variables of the machine, such as modifying it to read yml or data in the database

**Comment by clundin25** [comment]
I am closing this issue as it has gone stale. Please re-open it if you have any followup questions @0vally1 thanks!
