### ISSUE TITLE
google-auth doesn't have request tracing in aiohttp ClientSession

### ISSUE THREAD

**Issue by ananyo2012** [googleapis/google-auth-library-python#1061]
#### Environment details

  - OS: Windows 10
  - Python version: 3.8.10
  - pip version: 22.1.2
  - `google-auth` version: 2.6

#### Steps to reproduce

  1. Try to add `trace_configs` in `AuthorizedSession` call e.g. 
```python
async with LoggingAuthorizedSession(credentials(), trace_configs=[trace_config]) as session:
  response = await session.request("POST", url, headers=HEADERS, data=json.dumps(data))
```
  2. When you run your python server you will get errors like `exception ignored: TypeError("__init__() got an unexpected keyword argument 'trace_configs'")`

The issue is caused to this line

https://github.com/googleapis/google-auth-library-python/blob/main/google/auth/transport/_aiohttp_requests.py#L247

The fix should be easy by adding kwargs and using them in the parent class constructor call.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by sai-sunder-s** [comment]
Could you please provide a more detailed repro steps.

Also, please note that [_aiohttp_requests.py](https://github.com/googleapis/google-auth-library-python/blob/main/google/auth/transport/_aiohttp_requests.py) is experimental.
