### ISSUE TITLE
The auth.default() does not pick up SA name in GCE when created

### ISSUE THREAD

**Issue by mbruner** [googleapis/google-auth-library-python#1211]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: Ubuntu 16.04
  - Python version: 3.7.4
  - pip version: 22.3.1
  - `google-auth` version: 2.16.0

#### Steps to reproduce

  1. Run VM in GCE with some SA attached
  2. Install python, google-auth lib
  3. run 
```python
~$ python3
>>> import google.auth
>>> credentials, project_id = google.auth.default()
>>> print(credentials.service_account_email)
default
```
The SA email is set to `default` instead of a real SA name because `compute_engine.Credentials()` doesn't call the metadata server when created. It can be fixed from the consumer side too. However, it would be nice if the `google-auth` lib can take care of retrieving the correct SA email:
```python
>>> credentials = compute_engine.Credentials()
>>> print(credentials.service_account_email)
default

>>> import google.auth.transport.requests
>>> request = google.auth.transport.requests.Request()
>>> credentials.refresh(request)
>>> print(credentials.service_account_email)
gsa_name@project_name.iam.gserviceaccount.com
```

**Comment by clundin25** [comment]
Thanks for opening this issue @mbruner. I will take it to the team for discussion.

**Comment by clundin25** [comment]
Hi @mbruner 

We chatted and believe that the current behavior works as intended. Thank you for creating this issue! 

Feel free to add more context if you strongly disagree.

**Comment by jeffbryner** [comment]
I've experienced this as well as everyone in this thread  https://github.com/burnash/gspread/issues/820 and it's incredibly confusing. Some libraries like gspread appear to have worked around it but including it in the default behavior would alleviate a lot of issues and help folks use default service accounts.
