### ISSUE TITLE
Documentation version is lagging behind

### ISSUE THREAD

**Issue by GergelyKalmar** [googleapis/google-auth-library-python#1216]
Version 2.16.0 is completely absent (despite it being the latest version on PyPI) – https://googleapis.dev/python/google-auth/latest/ shows 
![image](https://user-images.githubusercontent.com/5601876/213863478-1efb47de-0de2-47f9-a724-c44dd74d5a84.png)

I'm also getting 404 errors when trying to build my documentation due to the Sphinx inventory file missing:
```
intersphinx inventory 'https://googleapis.dev/python/google-auth/2.16.0/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://googleapis.dev/python/google-auth/2.16.0/objects.inv
```

**Comment by clundin25** [comment]
Thanks for bringing this to our attention @GergelyKalmar. The 2.16.0 update has now deployed to the documentation webpage.

**Comment by GergelyKalmar** [comment]
Awesome, thank you!
