### ISSUE TITLE
deprecation warning from setuptools 67.3

### ISSUE THREAD

**Issue by davidszotten** [googleapis/google-auth-library-python#1229]
as of setuptools 67.3 (2023-02-13) there is a deprecation warning about implicit namespace packages

```
python -Wall -c 'import pkg_resources'
/path/to/tmp-7552ed82cdd0d3e/lib/python3.11/site-packages/pkg_resources/__init__.py:2804:
DeprecationWarning: Deprecated call to
`pkg_resources.declare_namespace('google')`. Implementing implicit namespace
packages (as specified in PEP 420) is preferred to
`pkg_resources.declare_namespace`. See
https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
declare_namespace(pkg)

```
(manually wrapped lines)

#### Environment details

  - OS: osx (any i presume)
  - Python version: 3.11.0
  - pip version: 23.0
  - `google-auth` version: 2.16.0

#### Steps to reproduce

  1. install latest google-auth and latest setuptools
  2. import `pkg_resources` (see above)

Thanks!

**Comment by kudlatyamroth** [comment]
is there any move on this?

**Comment by aqeelat** [comment]
@arithmetic1728 I understand this requires coordination with all of the other google python packages, but is there an internal issue regarding this?

**Comment by parthea** [comment]
Fixed in https://github.com/googleapis/google-auth-library-python/pull/1205
