### ISSUE TITLE
AttributeError: module 'google.auth.credentials' has no attribute 'CredentialsWithTokenUri'

### ISSUE THREAD

**Issue by lynnlynn2023** [googleapis/google-auth-library-python#1274]
#### Environment details

  - OS: MacOS 13.3 (22E252)
  - Python version: 3.10.10
  - pip version: 23.0.1
  - `google-auth` version: 1.33.0

#### Steps to reproduce

  1. quickstart.py suddenly cannot run (https://developers.google.com/calendar/api/quickstart/python)

#### Error Message
  File "/Users/*******/opt/anaconda3/lib/python3.10/site-packages/google/auth/external_account_authorized_user.py", line 52, in <module>
    credentials.CredentialsWithTokenUri,
AttributeError: module 'google.auth.credentials' has no attribute 'CredentialsWithTokenUri'

**Comment by lailufangchang** [comment]
if you are using tensorboard thequestion could be soved by turn the tensorboad version from higher to 2.9.0 or others
