### ISSUE TITLE
py.typed marker is missing

### ISSUE THREAD

**Issue by kshitij-enable** [googleapis/google-auth-library-python#1351]
#### Environment details

  - OS type and version: macOS Ventura 13.3 
  - Python version: 3.11
  - pip version: 23.1.2
  - google-auth : "^2.22.0"

#### Steps to reproduce
1.
```
from google.auth.transport import requests
from google.oauth2 import _client, id_token
```
  2. run mypy type checker

#### Stack trace
Skipping analyzing "google.oauth2": module is installed, but missing library stubs or py.typed marker 
Skipping analyzing "google.auth.transport": module is installed, but missing library stubs or py.typed marker

**Comment by borko-rajkovic** [comment]
You should try:

```sh
pip install google-auth-stubs
```
