### ISSUE TITLE
How to fetch id_token using google auth code

### ISSUE THREAD

**Issue by sophie-pan** [googleapis/google-auth-library-python#1373]
I'm getting a google auth code through my frontent (React) and sending it to my backend (Flask).

To retrieve the `id_token` with the auth code, i am using Google API since i couldn't find an equivalent in `google-auth` lib. Is there one ?
```
requests.post(
    "https://oauth2.googleapis.com/token",
    data={
        "code": auth_code,
        "client_id": self.client_id,
        "client_secret": self.client_secret,
        "redirect_uri": self.client_redirect_uri,
        "grant_type": "authorization_code",
    },
)
response_data = response.json()
g_id_token = response_data.get("id_token")
```

**Comment by arithmetic1728** [comment]
There is no equivalent in this lib. This lib only supports getting an ID token if you already have the refresh token.
