### ISSUE TITLE
How to change credentials subject when using GOOGLE_OAUTH_ACCESS_TOKEN

### ISSUE THREAD

**Issue by sgrzemski** [googleapis/google-auth-library-python#1378]
Hello,

I am trying to use this library with the token I get from the federated workload identities. I am able to create the Credentials object with the `GOOGLE_OAUTH_ACCESS_TOKEN`, but I cannot find a way to impersonate as a other user. With `GOOGLE_APPLICATION_CREDENTIALS ` I just used the `default()` method and then `with_subject` on the created credentials. How can I do the same with oauth2.credentials?

Kind regards,
Szymon

**Comment by arithmetic1728** [comment]
It's not clear to me what you want to achieve. 

Regarding impersonation, you can use google.oauth2.credential to impersonate a service account credential using google.auth.impersonated_credentials.Credentials class. https://github.com/googleapis/google-auth-library-python/blob/main/google/auth/impersonated_credentials.py#L119

**Comment by sgrzemski** [comment]
With the default credentials, I am using the `with_subject` method to change the subject to a group email and then use `googleapiclient.discovery` to read group membership from Google Admin API. I cannot impersonate it as a service account, because it's not a service account, so I cannot use `impersonated_credentials` tbh. Sample code I am trying:
```python
import os
from google.auth import impersonated_credentials
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

SCOPES = ['https://www.googleapis.com/auth/admin.directory.group.member.readonly']

oauth_creds = Credentials(token=os.getenv('GOOGLE_OAUTH_ACCESS_TOKEN'), scopes=SCOPES)
impersonated_creds = impersonated_credentials.Credentials(source_credentials=oauth_creds, target_scopes=SCOPES, target_principal='groupX@mydomain.com')

service = build('admin', 'directory_v1', static_discovery=False, num_retries=3, credentials=impersonated_creds)
response = service.members().list(groupKey='groupY@mydomain.com', maxResults=200).execute()
members = response['members']
print(members)
```

VERSUS the code that actually works:
```python
import os
from google.auth import default
from googleapiclient.discovery import build

SCOPES = ['https://www.googleapis.com/auth/admin.directory.group.member.readonly']

default_credentials, project_id = default(SCOPES)
subject_creds = default_credentials.with_subject(os.getenv('groupX@mydomain.com'))

service = build('admin', 'directory_v1', static_discovery=False, num_retries=3, credentials=subject_creds)
response = service.members().list(groupKey='groupY@mydomain.com', maxResults=200).execute()
members = response['members']
print(members)
```

**Comment by arithmetic1728** [comment]
Only user credential and service account can be the source credential for impersonation. I don't think federated workload identities is a supported feature.
