### ISSUE TITLE
Getting Keyerrror _refresh_handler with old tokens

### ISSUE THREAD

**Issue by sompodsign** [googleapis/google-auth-library-python#1444]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
![image](https://github.com/googleapis/google-auth-library-python/assets/47793716/24b218ae-5b14-45db-b94c-e3bff98bd6f3)

**Comment by clundin25** [comment]
Hi @sompodsign,

Thank you for this issue. Do you have any more details on how the token got into this state?

**Comment by sompodsign** [comment]
Thanks!. I can see the update on main branch. Could you please let me know how the release is work and when the fix is going to be released?

**Comment by clundin25** [comment]
We have been in a release freeze since Dec 14. This freeze expires tonight, at 12am PST. We will cut a release tomorrow, on Jan 3rd.

Thanks!

**Comment by clundin25** [comment]
Release v2.26.0 with the fix is now out! Feel free to re-open should the issue continue. Thanks!
