### ISSUE TITLE
Google Cloud credentials already set but still showing it is not set

### ISSUE THREAD

**Issue by subins829** [googleapis/google-auth-library-python#1459]
'Your application is authenticating by using local Application Default Credentials. The fcm.googleapis.com API requires a quota project, which is not set by default. To learn how to set your quota project, see https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds .'

Already set the quote project and commands related to that already run.

still showing this error
Please help!!

![image](https://github.com/googleapis/google-auth-library-python/assets/90414446/0d8dd10d-980b-44aa-933f-b2a4a6ae5e48)
![image](https://github.com/googleapis/google-auth-library-python/assets/90414446/44f1610d-e5e9-4b0f-9f24-cea150e6c172)

**Comment by TimurSadykov** [comment]
Please reopen if the question is still relevant.
