### ISSUE TITLE
Readme conflicts with `setup.py` about Python version support

### ISSUE THREAD

**Issue by akx** [googleapis/google-auth-library-python#1568]
The README claims that releases after January 2024 will only support Python 3.8+, but the package is still marked to support Python 3.7+.

Can you clarify what the plans are for dropping Python 3.7 support for good?

#### Environment details

  - OS: Irrelevant
  - Python version: see below
  - pip version: Irrelevant
  - `google-auth` version: 2.27 (January 2024) forward

#### Steps to reproduce

1. Read the README about Python version support: https://github.com/googleapis/google-auth-library-python?tab=readme-ov-file#supported-python-versions
2. Read the `setup.py` about Python version support: https://github.com/googleapis/google-auth-library-python/blob/40b9ed91a6b01948561cfc71edaaabdd7f362f17/setup.py#L64

**Comment by westarle** [comment]
We are working to move to Python 3.8, unfortunately I don't have a specific timeline to share.  I don't think it would be helpful to change the warning note at this point.
