### ISSUE TITLE
Support Elliptic curve signatures in JWT module

### ISSUE THREAD

**Issue by ptone** [googleapis/google-auth-library-python#157]
Currently

[https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/google/auth/crypt.py][1]

Only supports RSA

It would be great to add support for ES* such as ES256 signing algorithms as well

[1]: https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/709953d34c0c93744606a38e84abce557e73dfcb/google/auth/crypt.py

**Comment by dhermes** [comment]
@ptone Can you point to some docs for Google Auth services that accept elliptic curve signed JWTs?

**Comment by jonparrott** [comment]
@dhermes confirmed internally that a new (unannounced) service will support these. This isn't critical priority, but we should do this.

**Comment by engelke** [comment]
Cloud IAP provides JWT signed with ES256 only.
