### ISSUE TITLE
Getting a refresh token with serverAuthCode results in error

### ISSUE THREAD

**Issue by ajram23** [googleapis/google-auth-library-python#1585]
#### Environment details

  - OS: MacOS
  - Python version: 3.12.4
  - pip version: pip 24.0
  - `google-auth` version:1.2.0

Mac Client - GoogleSign 7.1 / Python -> google_api_python_client==2.132.0, google_auth_oauthlib==

#### Steps to reproduce

  1. Use Google-SignIn iOS to get serverAuth
  2. Send it to the server. Here is the code

```
CLIENT_SECRET_FILE = os.path.join(basedir, 'credentials.json')                     
                                                                                   
@app.route('/auth', methods=['POST'])                                              
def authenticate():                                                                
    auth_code = request.form.get('auth_code')                                      
    required_scopes = request.form.get('scopes')                                   
                                                                                   
    if not request.headers.get('X-Requested-With'):                                
        abort(403)                                                                 
                                                                                   
    try:                                                                           
        print(auth_code)                                                                                                                                              
        scopes = [scope.strip() for scope in required_scopes.split(',')] if required_scopes else []
        print(f"Scopes: {scopes}")                                                 
        print("Getting credentials")                                               
        flow = Flow.from_client_secrets_file(CLIENT_SECRET_FILE, scopes=scopes, redirect_uri="postmessage")
        print(f"Flow: {flow}")                                                     
        credentials = flow.fetch_token(code=auth_code)                             
        print("Got credentials!")    
```

Generate this log

> Inside authenticate
> Scopes: ['https://www.googleapis.com/auth/contacts']
> Getting credentials
> Flow: <google_auth_oauthlib.flow.Flow object at 0x105b28fb0>
> Error during authentication!
> (redirect_uri_mismatch) Bad Request

What is the right way to use the serverAuthCode from the client to get a refresh & access token in the server?

**Comment by arithmetic1728** [comment]
I don't think our library supports getting an access token from auth code, and we don't intent to support this. You may need to find other library to achieve this.

The error complains that your redirect_uri mismatch. You can change the `redirect_uri` to the exact uri you registered in cloud console when you obtain the client id file, and give it a try, however it might still doesn't work.

**Comment by ajram23** [comment]
@arithmetic1728 I have tried that. I guess then the question is simple, you have deprecated the library mentioned in this page https://developers.google.com/identity/sign-in/ios/offline-access and your new library doesnt support this. Your client teams can't help https://github.com/google/GoogleSignIn-iOS/issues/466, another team member suggests I go to paid support. So what happens to this use case? Do you have recommendations on other libraries?

**Comment by arithmetic1728** [comment]
@ajram23 I think you can follow this answer: https://stackoverflow.com/a/75929695. The `endpoint` is `https://oauth2.googleapis.com/token`.

**Comment by ajram23** [comment]
Thank you for the tip, let me try this out and get back to you @arithmetic1728

**Comment by ajram23** [comment]
@arithmetic1728 this did the trick! God bless you! Whats interesting is that "offline" scope is not even needed in fact generates an error. Will document it in a post so other can find it! Thanks again!
