### ISSUE TITLE
credentials.refresh(request) hangs on connection failure

### ISSUE THREAD

**Issue by luiz-telles** [googleapis/google-auth-library-python#1602]
When the credentials.refresh(request) function encounters a network connection failure, it becomes unresponsive and does not time out or raise an exception, causing the application to hang indefinitely. The expected behavior is for the function to either raise an exception or return a failure status within a reasonable timeout period, allowing the program to handle the error gracefully.

#### Environment details

  - OS:
  - Python version: 3.9.18
  - pip version: 21.2.3
  - `google-auth` version: 2.35.0

#### Steps to reproduce

 
1. Set up a firewall to silently drop packets to oauth2.googleapis.com.

2. Run the following commands:
   
    import google.auth.transport.requests
    from google.oauth2 import service_account
   credentials = service_account.Credentials.from_service_account_file(arguments.filename, scopes=SCOPES)
   request = google.auth.transport.requests.Request()
   credentials.refresh(request)

3- As noted in the https://requests.readthedocs.io/en/latest/user/advanced/#timeouts requests do not timeout by default unless explicitly set, causing the function to hang indefinitely without error in this case of connection failure.
"By default, requests do not time out unless a timeout value is set explicitly. Without a timeout, your code may hang for minutes or more"

"The connect timeout applies to each connection attempt to an IP address. If multiple addresses exist for a domain name, the underlying urllib3 will try each address sequentially until one successfully connects"

4- To avoid indefinite hanging of requests you could add a timeout to all requests-based calls .Example google/oauth2/_client.py.

    for _ in retries:
        response = request(
            method="POST", url=token_uri, headers=headers_to_use, body=body, timeout=timeout=(3, 5), **kwargs
        )

**Comment by harkamaljot** [comment]
Currently, the default timeout is set to 120 seconds and each time request is made, it is being passed here:  https://github.com/googleapis/google-auth-library-python/blob/main/google/auth/transport/requests.py#L187.  However, given the large timeout value, retries configured in google/oauth2/_client.py and multiple ip addresses for oauth2.googleapis.com the call takes about 7 mins before it throws an error.

**Comment by luiz-telles** [comment]
harkamaljot, you are correct, thank you.  Is it possible change this timeout value for: 
 
credentials = service_account.Credentials.from_service_account_file( 'service-account.json', scopes=SCOPES)
  request = google.auth.transport.requests.Request()
  credentials.refresh(request)
  return credentials.token

https://firebase.google.com/docs/cloud-messaging/migrate-v1#use-credentials-to-mint-access-tokens

**Comment by sai-sunder-s** [comment]
Another option is to totally skip making a network call to get a token. You could use [self-signed-jwt](https://github.com/googleapis/google-auth-library-python/blob/8cf1cb1663fccd03ea17a1bf055d862bddf61406/google/oauth2/service_account.py#L308). The token is created by the library itself instead of calling an endpoint. So something like:

```
import google.auth.transport.requests
from google.oauth2 import service_account
credentials = service_account.Credentials.from_service_account_file(arguments.filename, scopes=SCOPES)
credentials = credentials.with_always_use_jwt_access(true)
request = google.auth.transport.requests.Request()
credentials.refresh(request)
```

**Comment by sai-sunder-s** [comment]
Please reopen if the suggested solution doesn't work for you.
