### ISSUE TITLE
Add Support for IAP certs

### ISSUE THREAD

**Issue by venkashank** [googleapis/google-auth-library-python#1606]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

This library can not be used with IAP and requires following these snippets. 
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/iap

 **Describe the solution you'd like**
Please add IAP support directly to this library. 

 **Describe alternatives you've considered**

I have patched the _GOOGLE_OAUTH2_CERTS_URL to follow to the public url: https://www.gstatic.com/iap/verify/public_key

**Comment by sai-sunder-s** [comment]
@venkashank could you please clarify what functionality exactly you are looking for to be implemented in this library?

Are you looking for IAP public certs to be supported similar to [this](https://github.com/googleapis/google-auth-library-python/blob/484c8db151690a4ae7b6b0ae38db0a8ede88df69/google/oauth2/id_token.py#L67C1-L76C2)?

**Comment by venkashank** [comment]
Hi Sai,

Correct! I am currently patching that code to manually insert the IAP url.

**Comment by sai-sunder-s** [comment]
Could you please provide a code snippet showing how you are using this library? That will help us to understand the issue better.

**Comment by sai-sunder-s** [comment]
If you are still blocked, please reopen the issue with a code snippet showing how you are using the library.
