### ISSUE TITLE
Google Cloud Documentation out of Date and no sample code for Django

### ISSUE THREAD

**Issue by lanec** [googleapis/google-auth-library-python#181]
Team,

The official Google documentation for interacting with the Gmail API references the now unsupported Oauth2client library.  (e.g. https://developers.google.com/api-client-library/python/guide/django)

Would you be able to provide me with any kind of sample Django implementation for your library?

**Comment by jonparrott** [comment]
This is dependent on `google-auth-oauthlib` going 1.0.0 and that hinges on @vchudnov-g's work. I'll let him comment on when this might be possible.

**Comment by lanec** [comment]
Thanks!  

The reason for my post is that the oauth2client, sample code, and the Google documentation all reference from a module named 'oauth2client.contrib.django_orm' that seems to have been depreciated in the oauth2client library.  

Without that everything I've been able to find to integrate it into Django no longer works.  I'm unsure if this is by design to push more developers to google-auth as it's been depreciated.

**Comment by jonparrott** [comment]
the stuff in `oauth2client` should still work, at least for a while. We won't be updating the django stuff for newer versions of django, however.

**Comment by lanec** [comment]
I downloaded the sample Django 1.3 project and tried to run it locally.  It ran into an error creating columns in a SQLite database and a MySQL database.  I tried another sample 1.9 project I found online and it had no requirements.txt file so when I installed the dependencies it called for it grabbed the latest version and had the same issue I had in our project where the module was missing.

**Comment by danyaljj** [comment]
+1 on updating the docs.

**Comment by jonparrott** [comment]
We're in the process of updating the docs for using google-api-client-python with google-auth, starting with the YouTube API docs. Stay tuned.

**Comment by vchudnov-g** [comment]
@jonparrott My auth work is being delayed behind some other projects, so we should not block on that to improve implementation/usability in the meantime. Happy to talk more.

**Comment by PetroIvaniuk** [comment]
Hey guys, a year passed, but a problem still hasn't resolved yet.
Also, in the page https://developers.google.com/api-client-library/python/guide/aaa_oauth snippets of code with using the old library.

**Comment by sduskis** [comment]
I raised in issue on developers.google.com

**Comment by meredithslota** [comment]
Hi folks — thanks for filing this. The code samples for the Gmail API (and the code samples embedded in developers.google.com that are being referenced here) are sourced from another repo and a duplicate issue (re: replacing oauth2client with google-auth in the samples) already exists. I don't have the necessary permissions to move this issue there, but the duplicate issue is https://github.com/googleworkspace/python-samples/issues/10 In the comments of that issue, it looks like several samples have already been converted, but a handful remain. If they haven't gotten to your sample yet, please let them know in that thread. 

I'm going to close this in favor of that one. Thanks!
