### ISSUE TITLE
Can't connect to Cloud Endpoint using IDTokenCredentials

### ISSUE THREAD

**Issue by vbhavdal** [googleapis/google-auth-library-python#294]
Hello, I have an issue using this package to connect to a Google Cloud Endpoint. It looks like the problem is the iss claim in the jwt becomes "accounts.google.com" when it needs to be "https://accounts.google.com" in this case. (This value is set in the OpenAPI setup of the cloud endpoint, and in the documentation I've seen, "https://accounts.google.com" is used.)

I do this:

```
credentials = IDTokenCredentials.from_service_account_file(
    "service-account-file.json",
    target_audience="https://my-audience.com")
```
etc. and it leads to this iss claim:

`"iss": "accounts.google.com"
`

and 403. If I try:

`additional_claims={"iss": "https://accounts.google.com"}`

it leads to "The OAuth client was not found.". 

Now the thing is, I have been trying the code from the earlier PR for this (https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/234/files), and then it worked just fine with the same client code: 
`
"iss": "https://accounts.google.com",
`

So, does anyone have a workaround or fix for this?

google-cloud==0.34.0

**Comment by busunkim96** [comment]
@vbhavdal I know it's been a while since you filed the original issue. Do you know if this is still a problem?

**Comment by vbhavdal** [comment]
@busunkim96 Sorry, I can't answer that, I no longer work with the relevant code base.

**Comment by busunkim96** [comment]
The [OpenID Connect](https://developers.google.com/identity/protocols/OpenIDConnect#validatinganidtoken) documentation states that both `https://accounts.google.com` and `accounts.google.com` are valid.

The [discovery document](https://accounts.google.com/.well-known/openid-configuration) currently returns `https://accounts.google.com`.  

The Cloud Endpoints guide for Authentication with Google ID Token says to set `x-google-issuer` to `https://accounts.google.com`, so it makes sense that there would be an error when the `iss` is `accounts.google.com`. 

It looks like we should update Cloud Endpoints documentation.

**Comment by busunkim96** [comment]
Filed internal issue 139319528 to request the change to Cloud Endpoints documentation.

https://cloud.google.com/endpoints/docs/openapi/authenticating-users-google-id

**Comment by meredithslota** [comment]
The internal issue has been closed as a "Won't Fix" — I believe that the reference page has changed a great deal since this issue was filed and we missed closing this out. Thanks!
