### ISSUE TITLE
Get 404 when call Google Calendars with Service Account

### ISSUE THREAD

**Issue by haosdent** [googleapis/google-auth-library-python#312]
#### Environment details

  - OS: Ubuntu 16.04 and MacOS 10.11
  - Python version: Python 2.7 and Python 3.6
  - pip version: 18.1
  - `google-auth` version: 1.6.1

#### Steps to reproduce

  1. Use `from google.oauth2 import service_account` to call Google Calendar API to read events, got 404
  2. Use `from oauth2client import file, client, tools` to call Google Calendar API to read events, work as normal.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
Hi @haosdent,

It sounds like the service account doesn't have permission to access the calendar. The simplest solution is to [share the calendar(s)](https://support.google.com/calendar/answer/37082?hl=en) with the service account email. If you are on G Suite, you can also [give the service account domain-wide authority on the G Suite domain](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority).

**Comment by haosdent** [comment]
cool, it works! thx @busunkim96
