### ISSUE TITLE
No __init__.py in "google" folder

### ISSUE THREAD

**Issue by randalpinto** [googleapis/google-auth-library-python#315]
#### Environment details

  - OS: MacOS 10.13.6
  - Python version: 2.7.15
  - pip version: 18.1
  - `google-auth` version: 1.6.2

#### Steps to reproduce

If you run "pip install google-auth" the resulting package does not contain an __init__.py in the google directory. This is not a problem when the site-packages is the Python system one but in my case I have a different site-packages and when trying to run my code I would get:

ImportError: No module named google.oauth2.credentials

Hours later and lots of searching I finally found that when installing google-auth, a .pth file is installed (e.g.: google_auth-1.6.2-py3.7-nspkg.pth) in the sites-package however this only gets executed if your site-packages is in the list of sites. So in Python 2.7.15 you have to:

import site
site.addsitedir('/path/to/the/site-packages')

Is there a reason why google-auth is being distributed like this?

**Comment by theacodes** [comment]
This is intentional. google-auth is part of the `google` namespace package. Namespace packages *must* be install with pip into a proper site directory. I'm curious as to why your setup isn't properly processing your site-packages directory?
