### ISSUE TITLE
Certificate for key id xxxx not found: What could be the possible cause?

### ISSUE THREAD

**Issue by zhengzhong** [googleapis/google-auth-library-python#316]
Hi, I'm maintaining a website and its mobile apps (iOS and Android). For Google Sign-In in mobile app, I'm using google-auth Python package on the server side.

Since about one month ago, I started to receive error reports related to Google Sign-In from the server side. The error message looks like the following:

    Certificate for key id 728f4016652079b9ed99861bb09bafc5a45baa86 not found.

The server-side Google Sign-In authentication backend follows [this document](https://developers.google.com/identity/sign-in/android/backend-auth):

```python
from google.oauth2 import id_token
from google.auth.transport import requests

# ...

try:
    # The following line may raise ValueError with message: Certificate for key id xxxx not found.
    id_info = id_token.verify_oauth2_token(google_id_token, requests.Request())

    if id_info['aud'] not in VALID_CLIENT_IDS:
        logger.error('Invalid aud from Google ID token: %s', id_info['aud'])
        raise ValueError('Unverified audience.')
    # ...
except ValueError as exc:
    logger.error('Fail to verify Google ID token: %s', exc, extra={'request': request})
```

[Diving into the code](https://github.com/googleapis/google-auth-library-python/blob/master/google/oauth2/id_token.py#L139), I can see that ``verify_oauth2_token()`` function is fetching Google public certificates from the URL ``https://www.googleapis.com/oauth2/v1/certs``. It seems that sometimes, for some Google ID token sent from some Android device, the key id cannot be found in that URL.

Here are some other details which might be interesting:

- It seems that iOS app does not have this kind of issue. From the ``USER_AGENT`` header (``okhttp/3.11.0``), I can see that the error happens only in Android app. And it happens only in some Android device, not all.
- I was wondering if this happens only for Android phones from China (e.g. if they are connecting
  via a VPN). So I also checked the user IP address. But it turned out that those users were from Europe.
- Some key id is recurring again and again in the server error logs. For example, the key id ``aa436c3f63b281ce0d976da0b51a34860ff960eb`` is seen dozens of times, from November to now.

The website is running on the following environment:

- OS: Linux (CentOS 7) 64-bit
- Python version: 3.6.7
- pip version: 18.1
- `google-auth` version: 1.3.0 and 1.6.1

As I could not reproduce this issue either with my iPhone, or with my Android phone (Huawei P20, bought in France), I am completely stuck.

I don't think this is a bug in google-auth package. But I'm wondering if you have ever heard of this error, and what could be the possible cause of it?

Thanks in advance!

**Comment by dhermes** [comment]
I think the most likely explanation is that the certs at `https://www.googleapis.com/oauth2/v1/certs` are being rotated so every so often you're seeing tokens that were signed with certs that have been rotated out. (This is not official in any way, just a hunch.)

**Comment by zhengzhong** [comment]
Hi @dhermes , thank you for the reply! But still, something could not be explained:

- Why the error is happening only for Android app but not iOS? In fact, my iOS app has 3 times more users than the Android one.
- If the error happens only when a key id is rotated out of the public certs, why some key id is appearing in the error logs several times, in November and also in December?

One of my friends is having this issue now, and he bought his Android phone from Hongkong. This makes me think if it is possible that for some countries, Google Sign-In uses some different certs other than the public ones at `https://www.googleapis.com/oauth2/v1/certs`?

**Comment by busunkim96** [comment]
@zhengzhong Is this still happening?

This looks very similar to https://stackoverflow.com/questions/56882817/cors-error-access-control-allow-origin-missing-in-response-header-only-from-s. In that issue they are using `oauth2/v3/certs` rather than `oauth2/v1/certs`.

That issue was resolved with internal issue 136999458 last month.

I've opened a PR #365 to use `oauth2/v3/certs` as specified in the OpenID Connect configuration.

**Comment by zhengzhong** [comment]
Hi. I'd like to let you know that the issue is resolved. This library has nothing wrong. The issue was due to the fact that on Android device, I may get an expired ID token if the user has already signed in and I did not force to log him/her out. I explained the cause and posted the fix (in my Android app) here: https://stackoverflow.com/a/56742836/808898

I'll close this issue. Thanks for your help!

**Comment by jverkoey** [comment]
I ran into this issue just now as well, but the root cause was that I was using `id_token.verify_oauth2_token` instead of `id_token.verify_firebase_token` to verify a firebase-generated token.

**Comment by embray** [comment]
I'm having this problem as well, in France.  The thing I don't understand is it's asking for the key ID of my project's private key.  These are custom tokens created with `firebase_admin.auth.create_custom_token`.

**Comment by darpankattel** [comment]
thanks @jverkoey , we were using firebase services but using the `id_token.verify_oauth2_token` as you mentioned. Changing to `id_token.verify_firebase_token` and removing the GOOGLE CLIENT ID parameter helped in my case. Thanks.
