### ISSUE TITLE
OAuth Docs still point to oauth2client

### ISSUE THREAD

**Issue by collinanderson** [googleapis/google-auth-library-python#317]
The [oauth2client deprecation plan](https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html#post-deprecation-support) says:

> Since we are still iterating on user auth, some samples that use user auth will not be updated until we have settled on a final interface. If you find any samples you feel should be updated, please [file a bug](https://github.com/GoogleCloudPlatform/google-auth-library-python/issues).

The [Python OAuth 2.0 docs](https://developers.google.com/api-client-library/python/guide/aaa_oauth) have a bunch of sample code that use oauth2client, which is really confusing. (how do I rotate tokens?)

**Comment by busunkim96** [comment]
Hi @collinanderson. Thanks for the feedback. It's on our roadmap to remove oauth2client from the docs you linked. Some parts of the documentation do show [google-auth](https://developers.google.com/api-client-library/python/auth/web-app) rather than oauth2client. 

Did you have a particular question that isn't addressed by the [google-auth documentation](https://google-auth.readthedocs.io/en/latest/)?

**Comment by collinanderson** [comment]
how do I rotate tokens?

**Comment by busunkim96** [comment]
Are you using user credentials? If you provide a refresh_token, the library will refresh them automatically.

https://google-auth.readthedocs.io/en/latest/user-guide.html#user-credentials

>User credentials are typically obtained via OAuth 2.0. This library does not provide any direct support for obtaining user credentials, however, you can use user credentials with this library. You can use libraries such as oauthlib to obtain the access token. After you have an access token, you can create a google.oauth2.credentials.Credentials instance:
> 
```
credentials = google.oauth2.credentials.Credentials(
    'access_token',
    refresh_token='refresh_token',
    token_uri='token_uri',
    client_id='client_id',
    client_secret='client_secret')
```
> If you obtain a refresh token, you can also specify the refresh token and token URI to allow the credentials to be automatically refreshed:

**Comment by collinanderson** [comment]
I think the issue was when and how to persist that refresh token (or the whole credentials object) to file system or db. It's really confusing and not really documented.

**Comment by busunkim96** [comment]
Hi @collinanderson, storing credentials is currently outside the scope of the library.  We made the decision to leave that up to each individual application. There is additional discussion on this topic in #33.

https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html?highlight=storage#replacement

**Comment by collinanderson** [comment]
> leave that up to each individual application

right, but how do I even know what attributes I need to persist if I'm going to do it myself?

**Comment by busunkim96** [comment]
OAuth2 documentation has been updated to use `google-auth` and `google-auth-oauthlib` via https://github.com/googleapis/google-api-python-client/pull/738.

You can create a user credentials object using these methods:
*  from a map: [`from_authorized_user_info`](https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.credentials.html#google.oauth2.credentials.Credentials.from_authorized_user_info)
* from a json file [`from_authorized_user_file`](https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.credentials.html#google.oauth2.credentials.Credentials.from_authorized_user_file). 

There are 3 required fields:
https://github.com/googleapis/google-auth-library-python/blob/7a8641a7f0718c0dce413436f23691e8590face1/google/oauth2/credentials.py#L174

The full list of fields is listed here: https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.credentials.html#google.oauth2.credentials.Credentials
