### ISSUE TITLE
Add asyncio/tornado support

### ISSUE THREAD

**Issue by stalkerg** [googleapis/google-auth-library-python#321]
Subj. 
My current project was written on Tornado with async/await and I need to integrate google auth. 
Looks like current "transport" system not so good for async/await environment because you call it outside and I can't call async methods inside. 
Probably I can run request as an independent task on the loop but it ugly solution. 

Thanks.

**Comment by theacodes** [comment]
HI @stalkerg. It's something we want to do eventually, but we haven't found a feasible way of doing this while still supporting Python 2 users. Thankfully, we're on track to drop 2 support in 2020.

I'm going to close this issue for now, but know that it is (eventually) on our roadmap. 

In the meantime, if you're *super* enterprising most of the *private* code here is designed to transport agnostic, though might have some assumptions about blocking vs non-blocking behavior, so it may be possible to get a minimal set of functionality working for your use case.

**Comment by Lawouach** [comment]
Hi there,

Just wanted to raise a friendly flag of a Python3 only user who is looking forward for an async version indeed. The entire google suite of client libs is one of the last that doesn't support in some capacity async and it means we always have to craft around it somehow. It always feels brittle. So, again, looking forward some progress on this even though it means waiting until 2020.

Thanks.

**Comment by busunkim96** [comment]
Hi @Lawouach - the previous timeline still applies. We're looking forward to adding support in the next year.

**Comment by Lawouach** [comment]
Thanks. That's awesome news!

**Comment by boxysean** [comment]
I am also looking for async/await functionality from Google's python client libraries for use in a web server built on Tornado.

**Comment by stalkerg** [comment]
@Lawouach 2020 is here, do you have any news about async/await?

**Comment by kamyar** [comment]
Is there any development on this front? 
Also can you please reopen this issue as it is mentioned as a blocker for https://github.com/firebase/firebase-admin-python/issues/104 ?
To be honest we have been using firestore and lack of async is a very big downside of firestore.
If async supported is not planned for google services, It would be nice if we know beforehand so we can plan our migration to services that support it. Lack of this feature is causing us both money and product quality tbh.

**Comment by Lawouach** [comment]
@stalkerg nope.

To be fair I've moved to [Authlib](https://docs.authlib.org/en/latest/) for OAuth specifically. It doesn't help with other google libraries based on this one but I have no visibility on what Google does sadly :p
