### ISSUE TITLE
Documentation or example of using with OAuthLib

### ISSUE THREAD

**Issue by yuri-wisestamp** [googleapis/google-auth-library-python#327]
Seeing that documentation suggests using OAuthLib to obtain user credentials, and seeing that this is a very common use case, I'm finding it hard to find proper documentation integration. requests_oauthlib is sadly not an option as we're still using App Engine with Python 2.7.

Where can I find docs that show combined usage of both libs? Thanks

**Comment by busunkim96** [comment]
@yuri-wisestamp I may have missed something, but it looks like requests_oauthlib is available for python2.7. 

https://github.com/requests/requests-oauthlib/blob/800976faab3b827a42fa1cb80f13fcc03961d2c9/setup.py#L55-L56

Is there an incompatibility with the App Engine version you are using?

**Comment by busunkim96** [comment]
[google-auth-library-oauthlib ](https://github.com/googleapis/google-auth-library-python-oauthlib)may also work for your use case.

**Comment by busunkim96** [comment]
Closing as there has been no response. Please file a **new** issue if you are experiencing this issue.
