### ISSUE TITLE
Allow providing credentials thru an environment variable, without a file.

### ISSUE THREAD

**Issue by LEW21** [googleapis/google-auth-library-python#328]
**Is your feature request related to a problem? Please describe.**
I want to use Google Storage on Heroku. The correct way to configure a Heroku app is to use environment variables; there is no good way to provide a key file.

 **Describe the solution you'd like**
I'd prefer to set an environment variable (maybe `GOOGLE_APPLICATION_CREDENTIALS_JSON`) to the content of the key file.

 **Describe alternatives you've considered**
* I could add the file to the docker image, but I don't want to have any secrets there.
* During the app startup, I can save the content of the `GOOGLE_APPLICATION_CREDENTIALS_JSON` environment variable to a temp file, and set `GOOGLE_APPLICATION_CREDENTIALS` - but it's a custom solution, I'd prefer something standard.

**Comment by busunkim96** [comment]
I believe you can use `.from_service_account_info` (rather than `.from_service_account_file`) to load credential info from an environment variable.

```
service_account_info = json.load(os.environ.get('GOOGLE_APPLICATION_CREDENTIALS_JSON'))
credentials = service_account.Credentials.from_service_account_info(
    service_account_info)
```

See https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.service_account.html#google.oauth2.service_account.Credentials

**Comment by LEW21** [comment]
This is mostly about usage with existing tools and libraries, that just load default credentials, without an option to load a different kind of credentials manually. It would be nice if **default credentials supported loading from environment variable**. The whole point of default credentials is to not have to implement credentials loading again and again in every library / app, and to have a standard way of providing them.

**Comment by busunkim96** [comment]
Thank you for your feedback. Our auth libraries (across the seven languages we support) all implement a standard strategy when searching for credentials. You can read our documentation on that [here](https://cloud.google.com/docs/authentication/production).

For that reason, it would be unlikely for us to make this modification to only the Python Auth library. That said, we will make sure to keep this in mind in future discussions about our Auth libraries.

**Comment by frankV** [comment]
There are many sound reasons to keep the `credentials.json` file secure and use alternative methods for getting that info into the `Credentials` object. Better secrets management, OpsSec, etc.

If you need a better way, try the method below by replacing the call to secrets with your own flavor (a call to an `env var` maybe?)

```
from google.oauth2 import service_account

GOOGLE_APPLICATION_CREDENTIALS = service_account.Credentials.from_service_account_info(
        get_secret["GOOGLE_APPLICATION_CREDENTIALS"]
    )
```

One downside is having to pass this instance of `Credentials` around to every instance of a Google Cloud Client, but that's a small price knowing I can keep the original `credentials.json` file out of source control.
