### ISSUE TITLE
Merging  two Credentials

### ISSUE THREAD

**Issue by gsohler** [googleapis/google-auth-library-python#329]
Hi,

I followed the documented flow to create an

google.oauth2.credentials.Credentials

for scope: https://www.googleapis.com/auth/drive

using InstalledAppFlow and run_local_server 

and it got credentials1 which work just fine.

At a later point in time i created credentials for 

http://www.googleapis.com/auth/contacts.readonly'

and i got credentials2 which work just fine.

Is it possible to merge credentials1 and credentials2 such its valid for the merged scopes ?

I found some function 'with_claims'  but it appears to be available to an old version of the API.

Any help is appreciated

**Comment by busunkim96** [comment]
@gsohler  You can use `with_scopes` to copy a credential while adding additional scopes.

```scoped_credentials = credentials.with_scopes(scopes=['one', 'two'])```
[Documentation](https://google-auth.readthedocs.io/en/latest/reference/google.auth.credentials.html#google.auth.credentials.Scoped.with_scopes)

It is also possible to request both scopes when you first create the credentials.

**Comment by gsohler** [comment]
Hi Bu Sun Kim,

Thank you for your response.
I am sorry, I  do not understand the concept behind 'with_scopes'.
Why can i refer to the scope by telling its name only when all valuable
data is in google.oauth2.credentials.Credentials2 structure ?
Also i tried to use 'with_scopes by importing 'from google.auth import
credentials' but i could not access it

In My testprogram i have access to google drive already and i want to add
permission to contacts.readonly additionally:

Would be glad if you could help out.

Please find my test code attached

Best regards

========================

**Comment by busunkim96** [comment]
@gsohler I'm not able to see your code, could you please paste it into your response?

**Comment by gsohler** [comment]
Hi,

Please find enclosed my code:

#! /usr/bin/python

from googleapiclient.discovery import build
import os
import pickle
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth import credentials

# TODO ein einziges token.pickle


def get_cred(scopes):
creds = None
#picklefile='tokenpeople.pickle'
picklefile='token.pickle'
if os.path.exists(picklefile):
with open(picklefile, 'rb') as token:
creds = pickle.load(token)
print(creds)
print(scopes)
if not creds or not creds.valid or not creds.has_scopes(scopes):
if creds and creds.expired and creds.refresh_token:
creds.refresh(Request())
else:
flow = InstalledAppFlow.from_client_secrets_file(
'credentials.json', scopes)
new_creds = flow.run_local_server()
# Save the credentials for the next run
print("new",new_creds)
# creds_merged=creds.with_claims(new_creds) # with_claims does not exist
# creds=new_creds
creds_merged = credentials.with_scopes(scopes)
print("merged",creds_merged)
creds=creds_merged
with open(picklefile, 'wb') as fh:
pickle.dump(creds, fh)
return creds

scopes=['https://www.googleapis.com/auth/contacts.readonly']
creds=get_cred(scopes)


service = build(serviceName='people', version='v1', credentials=creds)

print(service.people())
# Call the People API
results = service.people().connections().list(
resourceName='people/me',
personFields='names,emailAddresses').execute()
connections = results.get('connections', [])



# https://developers.google.com/people/api/rest/v1/people
for person in connections:
names = person.get('names', [])
if names:
# displayName, givenName, familyName
name = names[0].get('displayName')
print(names)
print(name)

# vim: softtabstop=8 noexpandtab


Thank you

**Comment by busunkim96** [comment]
Apologies for taking a long time to get back to this.

You cannot take some credential A with scopes X and Y and credential B with scope Z and 'merge' them to get one credential C with scopes X, Y, and Z.

Since you are using user credentials, you will need to ask for all the scopes you need up front. This is because the user is asked to grant access to your app for those _specific_ scopes.

```py
from google_auth_oauthlib.flow import InstalledAppFlow

flow = InstalledAppFlow.from_client_secrets_file(
    'client_secrets.json',
    scopes=['profile', 'email'])
```
[google-auth-oauthlib-python documentation[(https://google-auth-oauthlib.readthedocs.io/en/latest/index.html)

`with_scopes` is for adding/changing scopes to service account credentials. See https://google-auth.readthedocs.io/en/latest/reference/google.auth.credentials.html?highlight=with_scopes#google.auth.credentials.Scoped
