### ISSUE TITLE
JWT in Authorization: Bearer Header

### ISSUE THREAD

**Issue by PaulMazzuca** [googleapis/google-auth-library-python#331]
Is it possible to use the id_token (JWT) in a request? By default the behavior uses the access_token, and I cannot seem to specify that the id_token should be used, as in the case of interacting with Google Cloud Endpoints, which only support the JWT.

```python
credentials = google.oauth2.credentials.Credentials(                                         
        None,                                                                                
        refresh_token='my_refresh_token',                       
        token_uri='https://oauth2.googleapis.com/token',
        client_id='my_client_id',
        client_secret='my_client_secret',                                            
        scopes=["profile"])                
                                   
authed_session = AuthorizedSession(credentials)                                              
# this get request always uses the access_token instead of id_token
authed_session.get("some.url.com")
```

**Comment by busunkim96** [comment]
Hi @PaulMazzuca, please take a look at our documentation on JWT credentials:

https://google-auth.readthedocs.io/en/latest/reference/google.auth.jwt.html#google.auth.jwt.Credentials

**Comment by PaulMazzuca** [comment]
Thanks for the reference, but I am not sure if those Credentials apply in this case, given that I am using the credentials from google.oauth2. My inputs are a refresh_token, client_id, and client_secret.  From that I can get a JWT and an access token, however the current code-base only allows for the get request to use the access token.  In the example I give above, the JWT will not be sent in the header.

**Comment by PaulMazzuca** [comment]
One way this could might solved is to override the "apply" function in google.oauth2.credentials.Credentials as so...

```        
 def apply(self, headers, token=None):
       # assumes instance variable of use_jwt
       if self.use_jwt:                    
             headers['authorization'] = 'Bearer {}'.format(self.id_token)
       else:
             super().apply(headers)
```

**Comment by busunkim96** [comment]
Ah sorry, I misunderstood. 

If you are using [Google ID token authentication](https://cloud.google.com/endpoints/docs/openapi/authentication-method#google_id_token_authentication) with Cloud Endpoints, you can use the IDTokenCredentials class.

> These credentials are largely similar to Credentials, but instead of using an OAuth 2.0 Access Token as the bearer token, they use an Open ID Connect ID Token as the bearer token. These credentials are useful when communicating to services that **require ID Tokens and can not accept access tokens.**

https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.service_account.html#google.oauth2.service_account.IDTokenCredentials

**Comment by PaulMazzuca** [comment]
Thanks again for the reply. I am still not sure this solves the issue, unless I am mistaken.  The use case input is a "refresh token" not a "service-account" key.   If you only have a refresh-token, how can you access a Google Cloud Endpoint API using this library?

The refresh token is obtained from a user OAuth2 login sequence. Normally, I would just use the access token to access the Google Cloud Endpoints, however Google Cloud Endpoints expects a JWT.  The IDTokenCredentials class expects a service-account key which is not available in this use case.

**Comment by dinvlad** [comment]
I'd like to add to this question - is it possible to starting with `google.auth.default()` `Credentials` and end up with an `id_token`? Otherwise, we have to detect the environment ourselves and use different strategy to generate it depending on the environment.

**Comment by mik-laj** [comment]
@dinvlad  I am afraid it is not supported. In my project, I implemented it on my side, but I didn't find time to contribute here
https://github.com/apache/airflow/blob/master/airflow/providers/google/common/utils/id_token_credentials.py.

**Comment by dinvlad** [comment]
@mik-laj thanks a lot! That does seem helpful

**Comment by dinvlad** [comment]
FWIW, I've created https://github.com/googleapis/google-auth-library-python/issues/590 to track this.

**Comment by arithmetic1728** [comment]
I don't think the ID Token from user credentials can be used in cloud run, because the audience is always the client id. The suggestion is https://github.com/googleapis/google-auth-library-python/issues/331#issuecomment-478183458 for service account, and https://github.com/googleapis/google-auth-library-python/blob/main/google/auth/compute_engine/credentials.py#L202 if it's on a GCE VM.
