### ISSUE TITLE
GCE_METADATA_ROOT should be called GCE_METADATA_HOST to be aligned with other client libraries

### ISSUE THREAD

**Issue by ensonic** [googleapis/google-auth-library-python#339]
file https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/environment_vars.py
contains `GCE_METADATA_ROOT` added in:
https://github.com/googleapis/google-auth-library-python/commit/b33b8021117db0d9ef80988cc7bb8ad58ecccf18

Client libs for other languages call it GCE_METADATA_HOST:
go: https://github.com/googleapis/google-cloud-go/blob/master/compute/metadata/metadata.go
java: https://github.com/googleapis/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
...

Maybe consider supporting both names for a transition?

**Comment by busunkim96** [comment]
I'd like to go through and check in the other languages before taking the change:

* NodeJS
* Ruby
* PHP
* C#
* C++ (? unsure if they have a separate auth library)
