### ISSUE TITLE
RefreshError after an hour even after having refresh and access token.

### ISSUE THREAD

**Issue by sbimochan** [googleapis/google-auth-library-python#345]
#### Environment details

  - OS: Mac OS
  - Python version: 3.6.7
  - pip version: 8.1.1
  - `google-auth` version: 1.5.1

#### Steps to reproduce

  1. exchange auth code
  2. store refresh and access tokens
 3. pass to 
```python
credentials = google.oauth2.credentials.Credentials(
        access_token,
        refresh_token=refresh_token,
        client_secret=settings.GOOGLE_CLIENT_SECRET,
        client_id=settings.GOOGLE_CLIENT_ID,
        token_uri=constant.TOKEN_URI,
    )
```
4. do some request with credentials. it will work
5. do some request after an hour. it will give refresh error.

**Comment by busunkim96** [comment]
Hi @sbimochan do you have the specific refresh error? It would help us determine what the issue is.

**Comment by sbimochan** [comment]
Sorry everyone, my team member mistakenly saved developer key as Client Secret key. It works.
 Closing it.
