### ISSUE TITLE
Serialize service_account.Credentials to JSON

### ISSUE THREAD

**Issue by VJalili** [googleapis/google-auth-library-python#350]
What is the simplest approach for serializing an object of type `google.oauth2.service_account.Credentials` to json?

I have tried the following: 

```python
creds = service_account.Credentials.from_service_account_file(
    creds_filename, 
    scopes=self.scops)
json_obj = json.dumps(creds.__dict__)
```
but that does not work because the signer does not implement a serializer: 

```
google.auth.crypt._cryptography_rsa.RSASigner object is not JSON serializable
```

I am trying to implement a custom JSONEncoder and decoder for `service_account.Credentials`, but I was wondering if there is exist a method out-of-box, or a simpler approach than custom encoder/decoder.

**Comment by theacodes** [comment]
These classes are intentionally *not* serializable. Service accounts are
*stateless* and the same `service-account.json` file can be used to
construct a new `service_account.Credentials` instance with the same
identity.

**Comment by VJalili** [comment]
what if the service of your application that uses credentials to access GCP is executed on a machine that does not have access to the path where `service-account.json` is persisted?

**Comment by theacodes** [comment]
You need to provide them through some means. I assume if you're attempting
to serialize credentials that you have *some* means of transmitting data to
that application. You can use `from_service_account_file` if its on disk or
`from_service_account_info` if its in memory.

**Comment by VJalili** [comment]
I am trying to avoid transferring `service-account.json` file, or the information within that, if that makes sense.

**Comment by theacodes** [comment]
Well, therein is the rub. if you *could* serialize service account
credentials you would end up with exactly the same info that's in the
`service-account.json` file.

One somewhat backwards and not recommended thing that you *can* do is get
an `access token` using service account credentials and then pass that
access token to the child app. This token would only be valid for one hour
and it's really not recommended.

**Comment by VJalili** [comment]
I prefer access token and I have been using them, but as I mentioned at https://github.com/googleapis/google-auth-library-python/issues/349, I also need to be able to sign blobs, which does not seem possible (at least to me) using access tokens.

**Comment by theacodes** [comment]
Yep, it's not. If you could, you'd effectively have a permissions hole as
being able to sign blobs means being able to sign a new token grant
assertion which could grant you new access tokens.

**Comment by VJalili** [comment]
That puzzles me; I am under the impression that an access token that is intended to only grant, e.g., read access to bucket X, should not authorize the service in the possession of the token with a different access, e.g., write access to the bucket X.

If that is a correct assumption, then using an access token that grants read access to bucket X, the service in possession of the token should be able to sign a blob that authorizes read access to bucket X.

**Comment by theacodes** [comment]
Unfortunately that's not the case. Due to the way signing for GCS signed
urls works, the same key used to sign the URL is the same key used to
obtain access tokens. Therefore, they have the same level of privilege -
you must give an application full rights to a service account to let it
generate GCS signed URLs.

Perhaps more illustratively:

1. Private key -> Signed Assertion Grant -> Access Token -> Read GCS Object.
2. Private key -> Signed URL -> Read GCS Object.

The trust root is the same in both cases, so you can't (typically) go from
Access Token -> Signed URL.

For you use case, I would recommend that you create a service account
specifically for this application that only has read access to the bucket
you'll be created signed URLs for.

**Comment by VJalili** [comment]
@theacodes hence one cannot use oauth2.0 credentials as described in the following to sign blobs?

https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials#sa-credentials-blob
