### ISSUE TITLE
use JSON file as string in python script

### ISSUE THREAD

**Issue by omrid594** [googleapis/google-auth-library-python#366]
Many versions to this question, none worked for me - 
Trying to read google spreadsheet, using `service account`.

used - 
```python
   json_string ="""{
  "type": "service_account",
  "project_id": "senrdcheckup",
  "private_key_id": "2e671ca3c2ebeeced478ca6255439c81dadde919",
  "private_key": "-----BEGIN PRIVATE KEY-----keycontentshere=\n-----END PRIVATE KEY-----\n",
  "client_email": "responses@seheckup.iam.gserviceaccount.com",
  "client_id": "1103439503200109",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/reses%40senkup.iam.gserviceaccount.com"}"""


    info = json.loads(json_string.replace('\n', " "))
    credentials = service_account.Credentials.from_service_account_info(info)
    client = gspread.authorize(credentials)
    sheet = client.open("LinkedIt_Responses").sheet1
    values_list = sheet.col_values(6)   
```

getting this error - 
```python exception
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
```

any suggestions about how to overcome this?

**Comment by busunkim96** [comment]
@omrid594 if those are actual credentials, please make sure to disable that service account. You don't want to expose credentials, as they provide access to your resources on GCP.

Is there a particular reason you're trying to load via `from_service_account_info`? If you are using a file, it's easier to just provide a path to `from_service_account_file`.

**Comment by busunkim96** [comment]
If you would like to load from a string, you should use a raw string to handle the `\n` correctly. I tested it out with one of my own service account keys and there were no errors in key deserialization.

```Python
json_string = r"paste in key contents here"
info = json.loads(json_string)
credentials = service_account.Credentials.from_service_account_info(info)
```

Loading from a file:
```Python
credentials = service_account.Credential.from_service_account_file('path/to/service_account.json')
```

**Comment by westarle** [comment]
@omrid594 I have just deleted all confidential key content that were visible in your initial comment as well as in revisions of the comment saved by Github.  I recommend you rotate your key, if it has access to any resources.

**Comment by omrid594** [comment]
> @omrid594 I have just deleted all confidential key content that were visible in your initial comment as well as in revisions of the comment saved by Github. I recommend you rotate your key, if it has access to any resources.

Thank you @westarle
