### ISSUE TITLE
Google Auth fails to load default project when inside of Docker with exported ~/.config

### ISSUE THREAD

**Issue by ramonmedeiros** [googleapis/google-auth-library-python#383]
#### Environment details

  - OS: mac
  - Python version: Python 3.7.5
  - pip version: 19.3.1
  - `google-auth` version:   1.7.0

#### Steps to reproduce
1) `gcloud auth application-default login`
2) `gcloud config set project ...`
3) In your machine, run:
```import google.auth;google.auth.default()```

It will return Credentials object and the default project

4) Open a docker image, python-3.7 alpine
5) Export your ~/.config and mount it
6) Run:
```import google.auth;google.auth.default()```
It does not return the default project 

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
Hi @ramonmedeiros. Are you seeing no project get returned? Or is it some other project?

**Comment by busunkim96** [comment]
On a second read, I'm don't think this particular flow is supported for getting a default project.

Please see https://hub.docker.com/r/google/cloud-sdk/ and https://github.com/GoogleCloudPlatform/cloud-sdk-docker for authenticating inside a docker image.

Thanks!
