### ISSUE TITLE
Oauth2 refresh token expires in 1 hour - is it b/c i'm currently testing ? (i.e. unverified app)

### ISSUE THREAD

**Issue by taewookim** [googleapis/google-auth-library-python#386]
I followed [this tutorial](https://developers.google.com/identity/protocols/OAuth2WebServer#example) EXACTLY, however

```
@app.route('/test')
def test_api_request():
  if 'credentials' not in flask.session:
    return flask.redirect('authorize')

  # Load credentials from the session.
  credentials = google.oauth2.credentials.Credentials(
      **flask.session['credentials'])

  drive = googleapiclient.discovery.build(
      API_SERVICE_NAME, API_VERSION, credentials=credentials)

  files = drive.files().list().execute()

  # Save credentials back to session in case access token was refreshed.
  # ACTION ITEM: In a production app, you likely want to save these
  #              credentials in a persistent database instead.
  flask.session['credentials'] = credentials_to_dict(credentials)

  return flask.jsonify(**files)
```

However in this part:

```
  credentials = google.oauth2.credentials.Credentials(
      **flask.session['credentials'])

```

The refresh token expires after an hour, with this error:

> The credentials do not contain the necessary fields need to refresh the access token. You must specify refresh_token, token_uri, client_id, and client_secret.

But clearly in the flask session the dict object is there:

```
{'client_id': '<COMMENTED_OUT>.apps.googleusercontent.com',
 'client_secret': '<COMMENTED_OUT>',
 'refresh_token': None,
 'scopes': ['https://spreadsheets.google.com/feeds',
            'https://www.googleapis.com/auth/drive',
            'https://mail.google.com/'],
 'token': '<COMMENTED_OUT>',
 'token_uri': 'https://oauth2.googleapis.com/token'}
```

Two questions 1) Do i need to manually "refresh" the refresh token? The comment in the tutorial says "Save credentials back to session in case access token was refreshed".. which implies that it's refreshed automatically

2) Is this because the app is still in unverified status?

**Comment by busunkim96** [comment]
Hi @taewookim. It looks like `refresh_token` is `None` in the dict object. Without a `refresh_token`, it isn't possible to refresh the credential. 

This [stackoverflow post](https://stackoverflow.com/questions/10827920/not-receiving-google-oauth-refresh-token) has a good list of options for how to get the `refresh_token`.  The easiest is probably to revoke access to your application. When the application requests access again it will get a refresh token for your account. You'll have to make sure to store the token as it won't be returned in subsequent requests.

Which tutorial were you looking at? Would you be able to provide a link?

**Comment by taewookim** [comment]
It seems not adding 

`prompt="screen"`

has a different behavior, and seems to solve this issue (also [mentioned here](https://github.com/googleapis/google-api-python-client/issues/213#issuecomment-205886341)).

it's only been only an hour or so, so i will leave this issue opened for now and will update as i keep testing

**Comment by taewookim** [comment]
been over 12 hrs.. so i guess that worked

closing issue

**Comment by Puyush6889** [comment]
@taewookim did you ever get this part of the question answered? 
`Is this because the app is still in unverified status?` 

I have a similar issue where the refresh token expire in 1hr but I don't see in docs anywhere the app has to be verified.
