### ISSUE TITLE
Using jwt.Credentials with discovery.build throws invalid credentials error

### ISSUE THREAD

**Issue by rakeshbabuseva** [googleapis/google-auth-library-python#395]
I want to migrate from oauth2client to google-auth, so I am trying to access the Google Drive using JWT token but couldn't able to get the access eventhough the jwt encoding went fine, am I missing anything ? 

```from google.auth import crypt
from google.auth import jwt
from googleapiclient import discovery
pkey=<Private_Key>
signer = crypt.RSASigner.from_string(pkey)
# getting the jwt.Credentials object
cred = jwt.Credentials(signer,  issuer='****@developer.gserviceaccount.com', subject="***@***.com", audience='https://accounts.google.com/o/oauth2/token', additional_claims={'scope': 'https://www.googleapis.com/auth/drive'})
drive = discovery.build('drive', 'v3', credentials=cred)
drive.files().get(fileId="****").execute()

Exception HttpError 401 when requesting https://www.googleapis.com/drive/v3/files/<file_id>?alt=json returned "Invalid Credentials```

Note: the above values like client id and issuer etc are worked with SignedJwtAssertionCredentials

**Comment by michaelawyu** [comment]
Hi @rakeshbabuseva,

If I understand your problem correctly, it seems to me that you are using a private key of a service account in your own project to sign the JWT while [Drive API explicitly requests that all requests to the Drive API must be authorized by an authenticated user](https://developers.google.com/drive/api/v3/about-auth#OAuth2Authorizing). In other words, you are using the RFC 7523/JWTs as Client Authentication workflow but the Drive API supports only the RFC 6749/OAuth2 Authorization Code workflow.

To solve the problem, use the Authorization Code flow to get an access token first and construct a credential using the `Credentials` class from `google.oauth2.credentials`.

You can find some examples here: [Drive API Quickstart/Python](https://developers.google.com/drive/api/v3/quickstart/python) (for command-line apps) and [Using OAuth 2.0 for Web Apps](https://developers.google.com/identity/protocols/OAuth2WebServer) (for web apps).

michaelawyu

**Comment by michaelawyu** [comment]
Hi @rakeshbabuseva !

I am now closing this issue due to its inactivity. Please feel free to reopen it if your problem persists.

michaelawyu
