### ISSUE TITLE
AttributeError in credentials.py

### ISSUE THREAD

**Issue by ryoichitaniguchi** [googleapis/google-auth-library-python#405]
Hello,

after updating `google-auth`  package from `v1.7.2` to `v1.8.0`  error occurred from `credentials.py`

stack-trace:
```
    range=RANGE).execute()
  File "/home/vagrant/py36/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/vagrant/py36/lib/python3.6/site-packages/googleapiclient/http.py", line 851, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/home/vagrant/py36/lib/python3.6/site-packages/googleapiclient/http.py", line 165, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/vagrant/py36/lib/python3.6/site-packages/google_auth_httplib2.py", line 187, in request
    self._request, method, uri, request_headers)
  File "/home/vagrant/py36/lib/python3.6/site-packages/google/auth/credentials.py", line 125, in before_request
    self.apply(headers)
  File "/home/vagrant/py36/lib/python3.6/site-packages/google/oauth2/credentials.py", line 185, in apply
    if self.quota_project_id is not None:
  File "/home/vagrant/py36/lib/python3.6/site-packages/google/oauth2/credentials.py", line 134, in quota_project_id
    return self._quota_project_id
AttributeError: 'Credentials' object has no attribute '_quota_project_id'
```

Trigger is googleapiclient.http.execute():
```
from googleapiclient.discovery import build
build('sheets', 'v4', credentials=creds).spreadsheets().values().get(spreadsheetId=SPREADSHEET_ID,range=RANGE).execute()
```

Downgrading google-auth to previous version (or avoid to refer this attribute) , error dissapeared. 

Some compatibility issue behind this?  Appreciate if someone let me know..

requirements condition
```
google-api-python-client
google-auth-httplib2
google-auth-oauthlib
google-auth
```

installed version from pip-list
```
google-api-python-client (1.7.11)
google-auth (1.8.0)     # or 1.8.1
google-auth-httplib2 (0.0.3)
google-auth-oauthlib (0.4.1)
```

**Comment by maxiller** [comment]
@ryoichitaniguchi thanks for the suggestion - rolling back to google-auth==1.7.2 workarounded for me

**Comment by busunkim96** [comment]
@maxiller @ryoichitaniguchi Were you using a pickled credential file?

Please do continue to use the downgraded version 1.7.2 - we will release a patch version soon with a fix. Thank you for your patience

**Comment by busunkim96** [comment]
[The Docs API quickstart](https://developers.google.com/docs/api/quickstart/python) seems to be representative of the sample style for APIs requiring user credentials. It pickles the credentials after the first run and reloads them when available.

**Comment by gayhub-dev** [comment]
damn! Thought something happen to my code!

**Comment by GustavoKatel** [comment]
I created a new credentials based on the old one:

```
new_cred = Credentials(token=cred.token, refresh_token=cred.refresh_token, id_token=cred.id_token, token_uri=cred.token_uri, client_id=cred.client_id, client_secret=cred.client_secret, scopes=cred.scopes)
```

Then I did pickle again to file

**Comment by busunkim96** [comment]
Hi - 

If you're running into this, please do either (1) or (2).

(1) Delete your pickled credentials file. The file will be named `token.pickle` if you followed a Google quickstart. Re-run the script (code that runs the authorization flow).
(2) Pin to a previous version `google-auth==1.7.2`

**Comment by maxiller** [comment]
> Hi -
> 
> If you're running into this, please do either (1) or (2).
> 
> (1) Delete your pickled credentials file. The file will be named `token.pickle` if you followed a Google quickstart. Re-run the script (code that runs the authorization flow).
> (2) Pin to a previous version `google-auth==1.7.2`

(1) did the trick. Thanks!

**Comment by ryoichitaniguchi** [comment]
worked with `google-auth==1.8.2` in my environment as well, thanks @busunkim96

**Comment by busunkim96** [comment]
Closing as the latest published library should work correctly with older pickled credentials files.
