### ISSUE TITLE
Breaking changes for impersonated_credentials between 1.6.3 and 1.7.0+

### ISSUE THREAD

**Issue by jonas-p** [googleapis/google-auth-library-python#416]
#### Environment details

  - OS: MacOS Mojave
  - Python version: 3.7.3
  - pip version: 19.0.3
  - `google-auth` version: 1.6.3, 1.7.0, 1.10.0

The default credentials are my user credentials (with the ServiceAccountTokenCreator role on the service account). 

#### Steps to reproduce
The following code works and produces a valid access token for the service account in version 1.6.3.

```python
from google.auth import impersonated_credentials, default
from google.auth.transport.requests import Request

sa = "<sa>@<project>.iam.gserviceaccount.com"
source_credentials, _ = default()
scopes = ["https://www.googleapis.com/auth/cloud-platform"]
creds = impersonated_credentials.Credentials(
    source_credentials=source_credentials, target_principal=sa, target_scopes=scopes
)

creds.refresh(Request())
print(creds.token)
```
After upgrading to 1.10.0, it fails to authenticate the service account due to invalid scopes.

```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    creds.refresh(Request())
  File "/google/lib/python3.7/site-packages/google/auth/impersonated_credentials.py", line 218, in refresh
    self._update_token(request)
  File "/google/lib/python3.7/site-packages/google/auth/impersonated_credentials.py", line 234, in _update_token
    self._source_credentials.refresh(request)
  File "/google/lib/python3.7/site-packages/google/oauth2/credentials.py", line 152, in refresh
    self._scopes,
  File "/google/lib/python3.7/site-packages/google/oauth2/_client.py", line 241, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/google/lib/python3.7/site-packages/google/oauth2/_client.py", line 115, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/google/lib/python3.7/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_scope: Bad Request', '{\n  "error": "invalid_scope",\n  "error_description": "Bad Request"\n}')
```

I traced this back to an google-auth upgrade from 1.6.3 to 1.7.0 (same error occurs).

**Comment by gpoulin** [comment]
Facing the same issue. Seems to be related with the fact that `impersonated_credentials` set the source credentials scopes to `['https://www.googleapis.com/auth/iam']` which is [undocumented](https://developers.google.com/identity/protocols/googlescopes) [ref](https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/impersonated_credentials.py#L208).

A work around is to reset the scope of the source credential

**Comment by tylervick** [comment]
Thanks @gpoulin - I confirmed the workaround as well.

Seeing the exact same issue - macOS impersonated creds scopes break on google-auth>1.6.3

**Comment by patriknordlen** [comment]
Adding some more context to this, the scope was always there but scopes were not actually requested until this change was made:
https://github.com/googleapis/google-auth-library-python/commit/49a18c43a5b39615bad90d23ab33a105fb656a6a?diff=split#diff-1b020acb6247d690d2ca64fcb04c8f53R241-R242

**Comment by busunkim96** [comment]
Thank you all for the investigation and details you've provided.

The general Google Cloud docs for impersonated credentials live [here](https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials). 

These docs state that `auth/iam/` scope and the `auth/cloud-platform/` scopes are valid. It doesn't go into detail as to if there's a difference between the two.

> scope: The OAuth 2.0 scope for the request. The following scopes are valid when calling the generateAccessToken API:
        * https://www.googleapis.com/auth/iam
        * https://www.googleapis.com/auth/cloud-platform

As @gpoulin points out the scope is not mentioned on the list of OAuth2 scopes at https://developers.google.com/identity/protocols/googlescopes, but it may just be out of date.

I will do some more investigation internally and update this issue.

**Comment by busunkim96** [comment]
Alright, so I think I've figured out the root cause. Impersonated credentials modify the scope of the source credential. This follows the guide  [here](https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials#sa-credentials-oauth). 

https://github.com/googleapis/google-auth-library-python/blob/31299e231912fe3c7a0e43dd3677c9f9391471c5/google/auth/impersonated_credentials.py#L208

Howecer `google.oauth2.credentials` *cannot* have their scopes modified after creation, so the source credential refresh fails with `invalid_scope`.
https://github.com/googleapis/google-auth-library-python/blob/31299e231912fe3c7a0e43dd3677c9f9391471c5/google/auth/impersonated_credentials.py#L224-L252
https://github.com/googleapis/google-auth-library-python/blob/31299e231912fe3c7a0e43dd3677c9f9391471c5/google/oauth2/service_account.py#L232-L239
