### ISSUE TITLE
Migrate docs to googleapis.dev

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-auth-library-python#431]
I noticed this repository is still sitting on readthedocs.  We need to move this over to googleapis.dev to be consistent with the rest of the libraries we publish.

**Comment by busunkim96** [comment]
The docs have been publishing to both places for a few versions now: https://googleapis.dev/python/google-auth/latest/index.html. The work remaining is to get the readthedocs docs to redirect to googleapis.dev.

**Comment by tswast** [comment]
Note: a search for "google auth python" still shows readthedocs as the top link:

![image](https://user-images.githubusercontent.com/247555/146273584-6fd442c1-bf92-4b78-92c9-110775979b5f.png)

**Comment by parthea** [comment]
Closing as obsolete
