### ISSUE TITLE
AdSense/googleapiclient Installed App Oauth2 Client Sample Update

### ISSUE THREAD

**Issue by KevinTydlacka** [googleapis/google-auth-library-python#456]
The [AdSense Management API python samples](https://github.com/googleads/googleads-adsense-examples) need to be updated to reflect the switch to `google-auth` from the deprecated `oath2client`...as well as to support python 3 in general. They rely on `apiclient/googleapiclient` `sample_tools.init()` which hasn't been updated to use `google-auth`.

One or two closed issues in `google-api-python-client` were related but didn't result in a resolution for this. Filing here per instructions at [oath2client deprecation document](https://googleapis.dev/python/google-auth/latest/oauth2client-deprecation.html). Might be something you guys want to punt to the AdSense or `googleapiclient` team but I wasn't sure. Looks like the functionality has moved to `additional_packages/google_auth_oauthlib/google_auth_oauthlib/flow.py`.

#### Environment details

  - OS: **All**
  - Python version: **3.6**
  - pip version: **All**
  - `google-auth-library-python` version: **1.11.2**
  - `google-api-python-client` version: **1.7.11**

#### Steps to reproduce

  1. Install `google-api-python-client`.
  2. Run `init()` from `googleapiclient/sample_tools.py`.
  3. Observe exception:
    `ImportError: googleapiclient.sample_tools requires oauth2client. Please install oauth2client and try again.`

**Comment by busunkim96** [comment]
@KevinTydlacka Thanks for filing an issue!

@benrkarl would you know of someone in Ads to redirect this to?

**Comment by BenRKarl** [comment]
@KevinTydlacka I see you already posted an issue on the AdSense library, which is definitely the correct place. I'll link this issue there for context and this one can be closed.
