### ISSUE TITLE
Samples for the Android Play Publisher API use oauth2client

### ISSUE THREAD

**Issue by simtel12** [googleapis/google-auth-library-python#478]
Just wanted to drop a line that the service account samples for the Android Play Publisher API are still using oauth2client: 

https://github.com/googlesamples/android-play-publisher-api/blob/master/v2/python/basic_list_apks_service_account.py
and
https://github.com/googlesamples/android-play-publisher-api/blob/master/v3/python/basic_list_apks_service_account.py

I don't think it's too difficult to convert to google-auth - I just wanted to let you know it was there.

Thanks,

**Comment by busunkim96** [comment]
Thanks for the report @simtel12! Unfortunately we still have a lot of samples that use oauth2client, but we plan to convert them all to google-auth eventually.

**Comment by mik-laj** [comment]
@busunkim96 Where can I find a ticket to follow these plans?

**Comment by busunkim96** [comment]
@mik-laj There is no open ticket right now, but I'll link one once it exists.

**Comment by busunkim96** [comment]
@simtel12 On a closer look it looks like these particular samples for Android Play Publisher *do* have a clear owner, so I'll reach out to them about updating their samples.

**Comment by busunkim96** [comment]
Passed this along to a developer who currently works on Android Play Publisher. Internal issue 153055037.

If you find more samples, feel free to file an issue here (or on google-api-python-client) and we'll continue to clean them. Thanks!
