### ISSUE TITLE
Invalid type for expiry when using GCE metadata server

### ISSUE THREAD

**Issue by danxmoran** [googleapis/google-auth-library-python#479]
#### Environment details

  - OS: Linux
  - Python version: 3.8.2
  - pip version: 20.0.2
  - `google-auth` version: 1.12.0

#### Steps to reproduce

  1. Create an ID token using the GCE metadata server:
      ```python
      from google.auth import compute_engine
      import google.auth.transport.requests
      request = google.auth.transport.requests.Request()
      target_audience = 'https://example.com'
      creds = compute_engine.IDTokenCredentials(request, target_audience, use_metadata_identity_endpoint=True)
      ```
  2. Try to use the credentials to authorize a request:
      ```python
      from google.auth.transport.requests import AuthorizedSession
      session = AuthorizedSession(credentials)
      response = session.get('https://example.com')
      ```

This results in an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/google/auth/credentials.py", line 66, in expired
    skewed_expiry = self.expiry - _helpers.CLOCK_SKEW
TypeError: unsupported operand type(s) for -: 'int' and 'datetime.timedelta'
```

I think the issue is on [this line](https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/compute_engine/credentials.py#L294). `payload["exp"]` should (apparently) be getting parsed into a `datetime.timedelta`

**Comment by arithmetic1728** [comment]
@danxmoran Thank you for reporting this bug. I created a PR to fix it.

**Comment by danxmoran** [comment]
Thanks @arithmetic1728, @busunkim96. I see that a release of 1.13.1 has already merged with the fix. How long does it usually take for releases to hit PyPI after the release PR merges here?

**Comment by arithmetic1728** [comment]
> Thanks @arithmetic1728, @busunkim96. I see that a release of 1.13.1 has already merged with the fix. How long does it usually take for releases to hit PyPI after the release PR merges here?

@danxmoran 1.13.1 is now on PyPI.
