### ISSUE TITLE
How to convert credentials to json 

### ISSUE THREAD

**Issue by Yajan** [googleapis/google-auth-library-python#489]
I am trying to store google.oauth2.credentials to json. How can it be done?

I get error as 
`'Credentials' object has no attribute 'to_json'`

**Comment by busunkim96** [comment]
What version of the library are you using? That feature has been available since [1.8.0](https://github.com/googleapis/google-auth-library-python/releases/tag/v1.8.0).

**Comment by Yajan** [comment]
I am sorry. I did not find it in document.

**Comment by azhuravlev1** [comment]
I have google-auth Version: 2.3.3 and I still get this error:

> AttributeError: 'Credentials' object has no attribute 'to_json'

**Comment by VictorTOON** [comment]
I'm using 2.0 and having the same issue

> 'Credentials' object has no attribute 'to_json'
