### ISSUE TITLE
Missing pyOpenSSL Dependency

### ISSUE THREAD

**Issue by smarlowucf** [googleapis/google-auth-library-python#551]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-auth-library-python/issues

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS:
  - Python version:
  - pip version:
  - `google-auth` version:

#### Steps to reproduce

  1. Missing pyOpenSSL dependency in setup.py

For the tests there is a requirement in https://github.com/googleapis/google-auth-library-python/blob/master/noxfile.py against pyOpenSSL. But there are imports for pyOpenSSL in multiple modules in the code. Should pyOpenSSL be added to the requirements in setup.py?

I created https://github.com/googleapis/google-auth-library-python/pull/550 with the proposal but wanted to get feedback from an issue first as I don't see this showing up in previous issues or pull requests.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
Hi @smarlowucf,

pyOpenSSL is not a requirement as it is only required for some transports. If you are for example only using gRPC you do not need pyOpenSSL.

We could potentially add it as an [`extra`](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) to make it easier to install.

**Comment by smarlowucf** [comment]
Hi @busunkim96. Okay, I agree it would be nice to have it as an extra so it's documented. I noticed it missing from running the test suite. I will close the PR.

**Comment by arithmetic1728** [comment]
`pyopenssl` is only needed if mTLS feature is enabled (disabled by default). To enable the feature, GOOGLE_API_USE_CLIENT_CERTIFICATE environment variable has to be set to "true". More details see https://google.aip.dev/auth/4114.

It is added to extra in #697

**Comment by merwok** [comment]
Hello!  Could the extra (existence and role) be documented in the readme or changelog?

**Comment by jessebrennan** [comment]
Even better, it would be great if the exception message referenced the extra.

**Comment by merwok** [comment]
Well to me it’s better to know about this in the release notes to do something before the code is deployed and causes an error message!
