### ISSUE TITLE
Support project_id for _AUTHORIZED_USER_TYPE

### ISSUE THREAD

**Issue by vimota** [googleapis/google-auth-library-python#558]
Right now, the load_credentials_from_file (which is used by google.auth.default()) always returns a `None` project id. This causes issues with libraries that only use the default() method for getting credentials (for example, [tensorflow_cloud fails on the user auth approach](https://github.com/tensorflow/cloud/issues/51) even if you set the project via the gcloud CLI).

It would be really helpful if either:
1. Project id was supported for credential files using the authorized user type (ie. load_credentials_from_file() read project_id from the file even for user auth type).
2. default() respected the project id set by the GOOGLE_PROJECT_ID env var or the one set by the gcloud cli.

Please let me know if I can clarify anything - or if there is any reason inherit about the above suggestion that doesn't make sense to implement.

**Comment by busunkim96** [comment]
I believe user credentials do not always have a project id (unlike service accounts, which always have a project).

(2) should already be true. See https://github.com/googleapis/google-auth-library-python/blob/9058f1fea680613d9717a62ee37dc294c11b9c8a/google/auth/_default.py#L306-L308 for the logic around this.

**Comment by vimota** [comment]
I totally missed that about (2) - makes sense thank you :)
