### ISSUE TITLE
How to change a `google.oauth2.service_account.Credentials` into a `google.auth.credentials.Credentials` object?

### ISSUE THREAD

**Issue by yohplala** [googleapis/google-auth-library-python#575]
Hi,

I use a service account to manage authentication with `google.oauth2`.

```python
from google.oauth2 import service_account
credentials = service_account.Credentials.from_service_account_file('/home/user/credentials.json')
```

I need to provide it with a new `http` object from [`build_http()`](https://github.com/googleapis/google-api-python-client/blob/d059ad881c7ae58c67931c48788d0bd7343ab16c/googleapiclient/http.py#L1891) in `googleapiclient/http.py`, by using 
[`authorized_http()`](https://github.com/googleapis/google-api-python-client/blob/d059ad881c7ae58c67931c48788d0bd7343ab16c/googleapiclient/_auth.py#L80) from `googleapiclient/_auth.py`.

However, within this `authorized_http()` method, one can see that a `google.auth.credentials.Credentials` object is expected, so that following method can be run.
```python
google_auth_httplib2.AuthorizedHttp(credentials, http=build_http())
```
But the credentials I get with the service account is a `google.oauth2.service_account.Credentials` object.

Please, how to change a `google.oauth2.service_account.Credentials` into a `google.auth.credentials.Credentials` object?

Thanks for your help.
Have a good day,
Bests,

**Comment by busunkim96** [comment]
All the credentials types base `google.auth.credentials.Credentials`. See https://github.com/googleapis/google-auth-library-python/blob/master/google/oauth2/service_account.py#L85 for example.

Are you getting an error when you try to use a service account credential to authorize the `httplib2.Http` instance?

**Comment by yohplala** [comment]
Hi @busunkim96 
Thanks for your help. I am sorry, I am unable to re-create the error. Everything works actually fine. I feel dumb, sorry for the disturbance.
Have a good day, and thanks again for your help.
Bests,
