### ISSUE TITLE
DefaultCredentialsError in a GKE Workload Identity setup due to MDS slow start up

### ISSUE THREAD

**Issue by 0xSage** [googleapis/google-auth-library-python#604]
#### Environment details

  - OS: GKE OS/container optimized OS
  - Python version: 3.7-slim
  - pip version: pip3
  - `google-auth` version: 1.21.0

#### Steps to reproduce

  1. Set up GKE with Workload Identity pool
  2. Have a Python app container, with code that relies on Python Auth to use some Cloud library, e.g. like Cloud Trace
  3. Deploy basic cluster. Experience a race condition `DefaultCredentialsError` that occurs ~50% of the time: 

[Reference code here](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/448)
```python
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
at default (/usr/local/lib/python3.7/site-packages/google/auth/_default.py:354)
at _create_composite_credentials (/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py:217)
at create_channel (/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py:280)
at create_channel (/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/transports/trace_service_grpc_transport.py:99)
at __init__ (/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/transports/trace_service_grpc_transport.py:69)
at __init__ (/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/trace_service_client.py:187)
at __init__ (/usr/local/lib/python3.7/site-packages/opentelemetry/exporter/cloud_trace/__init__.py:90)
at <module> (email_server.py:218)
```

This is likely* due to documented [WorkloadIdentity limitations](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#limitations): _"The GKE metadata server takes a few seconds to start to run on a newly created Pod. Therefore, attempts to authenticate or authorize using Workload Identity made within the first few seconds of a Pod's life may fail. Retrying the call will resolve the problem."_

Since this behavior is documented, I'm not sure if this issue should be a bug/feature request. Filing here after discussing with @busunkim96 

#### Potentially Related Issue

There exists a potentially related issue in GKE using the default credentials.

**Steps to Reproduce**
  1. Deploy GKE with the default Compute Engine Service Account (no workload identity)
  2. Have a Python app container, with code that relies on Python Auth to use some Cloud library, e.g. like Cloud Trace
  3. Deploy basic cluster. This time, `DefaultCredentialsError` occurs 100% of the time.

[Reference issue here](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/372)

**Comment by busunkim96** [comment]
@arithmetic1728 provided this work-around in an internal bug.

> It might be worth to try to increase the timeout when pinging metadata server by setting the `GCE_METADATA_TIMEOUT` environment variable to a larger value (10 seconds, 20 seconds, I am not sure). For workload identity the metadata server takes a much longer time to respond (issue 170985428), so this issue might be related.

https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/compute_engine/_metadata.py#L58

I've changed this to a "feature request" to capture getting the auth library to work nicely in this situation without the user having to set any environment variables.

**Comment by hadim** [comment]
I noticed a similar issue in GKE with workload identity (`1.18.20-gke.501`). However, it's hard to reproduce since it works 90% of the time. It seems like the error happens when the pod is using a high number of python processes (with `joblib`). My guess is that every new python process is calling the metadata server. Is there is any way to cache the credentials for the whole pod?

For now, I will increase `GCE_METADATA_TIMEOUT` and see whether it's good enough.

**Comment by hadim** [comment]
I am also realizing that my code uses probably too many processes and making a new call to the metadata server for each of them is likely overkill and probably add a lot of latency (explaining why my workload is much faster locally).

I guess it defeats the purpose of Workload Identity but do you think the best option in my case is to use `GOOGLE_APPLICATION_CREDENTIALS`? If yes then is there is a way to "populate" `GOOGLE_APPLICATION_CREDENTIALS` from the metadata server (so I don't have to add it as a secret)?

**Comment by TimurSadykov** [comment]
The fix for the issue is in progress, internal reference: go/auth-libraries-noping
