### ISSUE TITLE
v 1.21.2 supports python 2.7?

### ISSUE THREAD

**Issue by AdarShaked** [googleapis/google-auth-library-python#606]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hi, Do v 1.21.2 supports python 2.7?

**Comment by busunkim96** [comment]
Hi @AdarShaked,

Yes the latest library version is still compatible with 2.7 (although we strongly recommend you move to 3.6+).

Are you having trouble using the library with Python 2.7?

**Comment by AdarShaked** [comment]
yes.im having issues when installing from pypi  with pip 
(No module named google.auth.transport.requests)
maybe its problem in setup.py?

**Comment by tseaver** [comment]
@AdarShaked the `google/auth/transport/requests.py` module has:

```python
try:
    import requests
except ImportError as caught_exc:  # pragma: NO COVER
    import six

    six.raise_from(
        ImportError(
            "The requests library is not installed, please install the "
            "requests package to use the requests transport."
        ),
        caught_exc,
    )
```

See: https://googleapis.dev/python/google-auth/latest/user-guide.html#requests
