### ISSUE TITLE
Getting unsupported operand type(s) for -: 'str' and 'datetime.timedelta'

### ISSUE THREAD

**Issue by subhajeet2107** [googleapis/google-auth-library-python#666]
#### Environment details

  - OS: Ubuntu 18
  - Python version: 3.7
  - pip version:
  - `google-auth` version: 1.21.3

#### Steps to reproduce

  1. Create credentials from InstalledAppFlow
  2. While checking for credentials.expired with : if credentials and credentials.expired and credentials.refresh_token
  3. Getting unsupported operand type(s)  from line 68:  "skewed_expiry = self.expiry - _helpers.CLOCK_SKEW" in file: google/auth/credentials.py

Does this support python 3.7 ? getting unsupported operands error when credentials expiry is checked

**Comment by busunkim96** [comment]
Yep! 3.7 is supported. You can check the supported versions list in the descriptors / python_requires. https://pypi.org/project/google-auth/ 

It sounds like the library might be missing a conversion from str to datetime. Would you mind sharing a bit more ot the code you were using?

**Comment by subhajeet2107** [comment]
So i was initialising the Credentials class from json itself, and this caused problems:
Credentials class offers a to_json() method, after storing this output lets say to a json file and then recreating it causes this issue eg:
`
creds = Credentials(token='abc', refresh_token='xyz')
json_output = creds.to_json()

#Save this output somewhere like creds.json
#then load this again

import json
creds = Credentials(**json.loads('creds.json'))

#now if you try to check if credentials has expired, this happens, so calling: if creds.expired: pass
#will trigger the issue, this might be due to class attributes being set from JSON object, as JSON's expiry time attribute gets loaded as string in Credentials instead of a datetime object and when comparing this string to datetime operation while doing "self.expiry - _helpers.CLOCK_SKEW"  , this is my guess
`
In order to fix this, instead of loading the entire json object to Credentials class i simply loadded only required attributes except the expiry time, this solved the issue.
I would suggest 2 things, first provide a Credentials.from_json() method to easily create Credentials from JSON objects
Another suggestion is checking the type of self.expiry before comparing and throwing better error if self.expiry is not a datetime object

**Comment by busunkim96** [comment]
Apologies for the late response!

I think the easiest way to take care of this is to re-load the credentials using either `from_authorized_user_info` or `from_authorized_user_file`, as it will handle turning the expiry into a datetime. 

https://googleapis.dev/python/google-auth/latest/reference/google.oauth2.credentials.html#google.oauth2.credentials.Credentials.from_authorized_user_info

https://github.com/googleapis/google-auth-library-python/blob/306115d9dcf0b1806630563ae2d0aa40866966fb/google/oauth2/credentials.py#L282-L289

```py
import json

from google.oauth2.credentials import Credentials

creds = Credentials.from_authorized_user_file('creds.json')
```
