### ISSUE TITLE
IAP access token cannot be generated from application_default_credentials.json

### ISSUE THREAD

**Issue by franeksaww** [googleapis/google-auth-library-python#669]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-auth-library-python/issues

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Linux
  - Python version: 3.6.9
  - pip version: 9.0.1
  - `google-auth` version: 1.24.0

#### Steps to reproduce

1. Running this code or using https://cloud.google.com/iap/docs/authentication-howto#signing_in_to_the_application returns always: {'error': 'invalid_audience', 'error_description': 'The audience client and the client need to be in the same project.'}

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by franeksaww** [comment]
```
import google.auth
import requests
import json


CLIENT_ID = "some-client-id"


# use gcloud app default credentials if gcloud's util.py is patched


def id_token_from_default_creds(audience):
    cred, proj = google.auth.default()

    # data necessary for ID token
    client_id = cred.client_id
    client_secret = cred.client_secret
    refresh_token = str(cred.refresh_token)
    return id_token_from_refresh_token(client_id, client_secret, refresh_token, audience)


def id_token_from_refresh_token(client_id, client_secret, refresh_token, audience):
    oauth_token_base_url = "https://www.googleapis.com/oauth2/v4/token"
    payload = {"client_id": client_id, "client_secret": client_secret,
               "refresh_token": refresh_token, "grant_type": "refresh_token",
               "audience": audience}
    res = requests.post(oauth_token_base_url, data=payload)
    return str(json.loads(res.text))


id_token_from_default_creds(CLIENT_ID)
```

**Comment by busunkim96** [comment]
Hi @franeksaww,

Could you check what kind of credential is getting picked up by `google.auth.default()` by checking `type(cred)`?
