### ISSUE TITLE
Importing gmail address in google Oauth to the respective gmail account

### ISSUE THREAD

**Issue by Daniyaldehleh** [googleapis/google-auth-library-python#687]
I am using google-Oauth to login/sign up my user to my google projects. I'd like the users signing up to be imported to the google project's gmail account's contacts. What's the best way to go about it? I'm hoping for a cleaner & easier way than manually sending user's gmail from my backend to the gmail account via an api?

It would highly make sense for google OAuths to support such critical feature given the wide use of OAuth logins & gmail across websites.

However, I can't find any docs or pages on how to set up such a feature.

**Comment by busunkim96** [comment]
Hi,

I'm not sure I completely follow. Would you mind expanding a bit more? If I understand correctly, you are looking to create a list of email contacts for all users who have used OAuth2 to access your application? 

When you say "google project" are you referring to the project created in console.cloud.google.com?

**Comment by DaniyalDhz** [comment]
Exactly! you got it right. The users signing up with my OAuth of my google project from (console.developers.google.com) to be added to the project gmail account's contact list in (console.developers.google.com)

**Comment by busunkim96** [comment]
@silvolu @arithmetic1728 Could you take a look?

**Comment by arithmetic1728** [comment]
This is beyond the scope of this auth library. I think you need resource manager api, the description is here: https://cloud.google.com/resource-manager/docs/reference/essentialcontacts/rest#rest-resource:-v1beta1.projects.contacts. Specifically this method for getting the list of contacts:

```
GET /v1beta1/{parent=projects/*}/contacts
Lists the contacts that have been set on a resource.
```

I guess maybe this can be done via [python-resource-manager client library](https://github.com/googleapis/python-resource-manager).

**Comment by DaniyalDhz** [comment]
the problem is that I don't want to get a list or else I would've just look at my db but rather for the contacts to be automatically added to contact.google.com of the email to avoid any duplications

**Comment by DaniyalDhz** [comment]
lastly, as I couldn't find any answer on google:
if I "reset" my client secret key for my OAuth project, would I have to reapply for verification?

**Comment by DaniyalDhz** [comment]
![Screen Shot 2021-02-10 at 3 24 03 PM](https://user-images.githubusercontent.com/58639693/107567739-0fe6c780-6bb4-11eb-99d1-dfe75a186786.png)

**Comment by busunkim96** [comment]
@DaniyalDhz Please try one of the methods mentioned in https://github.com/googleapis/google-api-python-client/issues/1177 for getting in contact with the OAuth API verification folks.

**Comment by arithmetic1728** [comment]
closing the issue due to inactivity
