### ISSUE TITLE
How to check if user has been authenticated from google OAuth 2.0 web server

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-auth-library-python#702]
This [SO1](https://stackoverflow.com/questions/12262198/logged-in-on-both-a-website-and-a-chrome-extension) mentioned that the best way to secure a website from API calls is to check whether the user is logged in/authenticated before accepting any API Calls. In my case, I am using google OAuth 2.0 to login and access user's calendar.

After countless hours on checking how to log out a user with google OAuth 2.0 , I realized that if I were to logout user from my app, the user would be logged out of google too (really bad UX) hence not so common.

Therefore, how can I still apply the website advice w/o having a log out system? As every other security protocol I tired wasn't either possible or secure enough.

How can I check if the user is authenticated from a google OAuth 2.0, if so, accept POST requests?

As:

`if 'credentials' not in flask.session:
`resulted in:

`<SecureCookieSession {}>
`despite the user being logged in & session cookies being passed:
![Screen Shot 2021-02-16 at 12 21 27 PM](https://user-images.githubusercontent.com/58639693/108098653-9df9fc80-7051-11eb-90d7-b5227ec176c5.png)

**Comment by arithmetic1728** [comment]
Closing the issue since session management is not related to auth library. Auth lib is only used to fetch tokens.
