### ISSUE TITLE
Support Request: Authenticate through Raw Python Request?

### ISSUE THREAD

**Issue by Avnsx** [googleapis/google-auth-library-python#724]
Hello guys I'm trying to authenticate my python code to google and I've read through this entire page; https://google-auth.readthedocs.io/en/latest/user-guide.html and as far as I see there's no simple way I could just authenticate my python code to google, without having to use the "Credentials page of the Google Cloud Console" and adding some kind of api key or similar there. So I am wondering if there's a a simple way my app could just authenticate without doing that, - just as a normal user would on the google google login form for example - by just using E-Mail and Password; but preferably through simple python requests.

**Comment by busunkim96** [comment]
Hi @Avnsx,

Which API are you using? 

If you are developing locally with an API that accepts end user credentials, https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login is one option.

> Obtains user access credentials via a web flow and puts them in the well-known location for Application Default Credentials (ADC).
> This command is useful when you are developing code that would normally use a service account but need to run the code in a local development environment where it's easier to provide user credentials. The credentials will apply to all API calls that make use of the Application Default Credentials client library. Do not set the GOOGLE_APPLICATION_CREDENTIALS environment variable if you want to use the credentials generated by this command in your local development. This command tries to find a quota project from gcloud's context and write it to ADC so that Google client libraries can use it for billing and quota. Alternatively, you can use the --client-id-file flag. In this case, the project owning the client id will be used for billing and quota. You can create the client-id-file at https://console.cloud.google.com/apis/credentials.

The credentials produced by that command will get picked up by the auth library and used by default.

However depending on the API you may have to set up https://developers.google.com/identity/protocols/oauth2. https://developers.google.com/identity/protocols/oauth2/web-server has Python sample code.
