### ISSUE TITLE
jwt.encode() overrides the algorithm specified by the caller

### ISSUE THREAD

**Issue by hiranya911** [googleapis/google-auth-library-python#725]
The `jwt.encode()` function always set the `alg` JWT header to either ES256 or RS256, even if the caller had specified an explicit algorithm:

https://github.com/googleapis/google-auth-library-python/blob/48e8be3d59a47493e60f5b5d9f284b300979a11c/google/auth/jwt.py#L98-L101

This function should only set the `alg` header when the caller hasn't specified one. This is required to support some use cases in Firebase emulator, where we need the ability to mint JWTs with `alg` header values like `none`.

**Comment by hiranya911** [comment]
It might also make sense to read the exact `alg` header to use from the `google.auth.crypt.Signer` interface, since those concepts are close related. Something like:

```py
if 'alg' not in header:
    if signer.alg:
        header['alg'] = signer.alg
    elif es256 is not None and isinstance(signer, es256.ES256Signer): 
       header.update({"alg": "ES256"}) 
    else: 
       header.update({"alg": "RS256"})
```

Let me know if this makes sense, and I'd be happy to provide a PR to this effect.

**Comment by busunkim96** [comment]
@arithmetic1728 @silvolu PTAL

**Comment by hiranya911** [comment]
Also adding @yuchenshi and @samtstern from Firebase for visibility.

**Comment by arithmetic1728** [comment]
@hiranya911 I created a PR to use `alg` from header if provided.
