### ISSUE TITLE
Don't warn when gcloud credentials are used

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-auth-library-python#744]
The library raises a warning when folks use gcloud SDK credentials.

I believe it should be removed, given updated guidance in https://cloud.google.com/docs/authentication/best-practices-applications

https://github.com/googleapis/google-auth-library-python/blob/04c870a5bcc2c25433774a27280505d3413550e3/google/auth/_default.py#L60-L70

CC @silvolu @arithmetic1728

**Comment by silvolu** [comment]
The warning is still accurate: APIs that don't have a surface in the gcloud CLI won't work, and the quota is shared across all users so there could be quota exceeded errors.
The new guidance is consistent with the warning, as it says to specify a user owned billing project or client ID.

**Comment by arithmetic1728** [comment]
@busunkim96 This seems to be the right behavior. The gcloud users need to add `quota_project_id` to their `~/.config/gcloud/application_default_credentials.json` file, then the warning will go away.

I think if the user logs in again via `gcloud auth application-default login`, then the new json file will automatically have this field (it works for me). If this doesn't work, then the quota project id can be manually added via `gcloud auth application-default set-quota-project <the_quota_project_id>`.

**Comment by busunkim96** [comment]
Thanks all, I completely forgot that the warning was updated to be more specific. :) 

CC @tseaver
