### ISSUE TITLE
MetadataAPI errors

### ISSUE THREAD

**Issue by lechen26** [googleapis/google-auth-library-python#745]
Hi

we've switched a month ago to GKE workload identity which from my understanding prevents the use of the MetadataAPI.
until now we were using google-cloud-logging-handler==1.3 and now we've added also google-cloud-secret-manager==2.4.0

now we get the following error:
```
venv/lib/python3.8/site-packages/google/auth/compute_engine/credentials.py", line 117, in refresh six.raise_from(new_exc, caught_exc) File "<string>", line 3, in raise_from google.auth.exceptions.RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\nb'Not Found\\n'", <google.auth.transport.requests._Response object at 0x7fadb9e4e760>)
```
the thing is, the workload is able to use the Secret Manager and to fetch the secrets, etc.
the workload includes different service account then the default, which provides her the right access for GCP.

any idea?

**Comment by busunkim96** [comment]
Hi @lechen26,

One known issue with Workload Identity is that it takes a few seconds for the metadata server to become available. That can cause issues for client libraries which expect the metadata server to be available within a shorter timeframe. See https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#troubleshoot-timeout

Setting the environment variable `GCE_METADATA_TIMEOUT` to a bigger number may help.

https://github.com/googleapis/google-auth-library-python/blob/04c870a5bcc2c25433774a27280505d3413550e3/google/auth/compute_engine/_metadata.py#L57-L60

Bouncing over to @arithmetic1728 who has more expertise here.

**Comment by lechen26** [comment]
Thanks @busunkim96 .

i've tried the GCE_METADATA_TIMEOUT and it doesnt seems to look on it.

while setting on the deployment GCE_METADATA_TIMEOUT=60 i see the following log:
```
E 2021-05-02T07:20:21.407898426Z AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fe980116790>" raised exception!
I 2021-05-02T07:20:09.666234016Z Booting worker with pid: 8 
I 2021-05-02T07:20:09.661986589Z Using worker: sync 
I 2021-05-02T07:20:09.661794185Z Listening at: http://0.0.0.0:8000 (6) 
```

you can see that after 11 sec it throws the exception.
10x

**Comment by lechen26** [comment]
Hi @busunkim96 @arithmetic1728 

while reading the code here `google-auth-library-python/google/auth/compute_engine/_metadata.py`  seems like the timeout indeed shouldnt help me here as the problem is Not that the Metadata Serveris notreachable.
the Excexption thrown after recieveing response from the metadata server which is later seen as 'HTTP 404: Not Found'

every time new Pod starts i see this for a few seconds and then pod continue to work as expected.

any idea?...
10x

**Comment by arithmetic1728** [comment]
@lechen26 Maybe at the very beginning of your app, you can do:
```
import google.auth.transport.requests
import google.auth.compute_engine._metadata

req = google.auth.transport.requests.Request()
google.auth.compute_engine._metadata.ping(req)
```
Here `google.auth.compute_engine._metadata.ping(req)` will try to ping the metadata server for 3 times with a timeout of `GCE_METADATA_TIMEOUT` seconds (so it will delay the app for at most 3*3=9 seconds). Let me know if this works for you. Thanks!

**Comment by arithmetic1728** [comment]
Closing the issue. Please reopen the issue if the problem persists. Thanks.
