### ISSUE TITLE
Inconsistencies when fetching id tokens

### ISSUE THREAD

**Issue by jceresini** [googleapis/google-auth-library-python#746]
#### Environment details

  - OS: Macos
  - Python version: 3.7.8 
  - pip version: 20.1.1
  - `google-auth` version: 1.30.0

#### Steps to reproduce

  1. Run the example code on a compute instance running as a given service account
  2. Note that the `azp` field in the token is the `unique_id` of the service account
  3. Export a service account key for the same service account, and save it locally
  4. Set/export the GOOGLE_APPLICATION_CREDENTIALS env var to be the location of the service account key file
  5. Run the example code locally
  6. Note that the `azp` field is now the full email address of the service account

```python
from google.auth.transport import requests
from google.oauth2.id_token import fetch_id_token
import base64

audience = 'my_app_name'
token = fetch_id_token(requests.Request(), audience)

payload = token.split('.')[1] + "===" # b64decode chokes on missing padding, but truncates extra padding

print(base64.b64decode(payload))
```

My intention is to use the id_token to assumeRole into an AWS account. On the AWS side, i can setup a role with the following trust relationship:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Federated": "accounts.google.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "accounts.google.com:aud": "test-svc-acct@test-project.iam.gserviceaccount.com"
        }
      }
    }
  ]
}
```

Note that AWS uses the `azp` field as the audience if it is set, otherwise it uses the `aud` field. The inconsistencies mean i need to either accept both the email address and the unique ID, or i need to be sure my application always runs the same way (either with access to a metadata service, or without)

**Comment by arithmetic1728** [comment]
@parthea This is server side issue. It looks like compute engine metadata server and service account token endpoint have different implementations. The library itself just queries the corresponding endpoint to get tokens and it has limited control of what the token looks like.
