### ISSUE TITLE
ERROR: The caller does not have permissions for firebase Dynamic link Analytics Rest API

### ISSUE THREAD

**Issue by George-Kihara** [googleapis/google-auth-library-python#753]
I keep getting this error:

{
    "error": {
        "code": 403,
        "message": "The caller does not have permission",
        "status": "PERMISSION_DENIED"
    }
}

**Comment by danoscarmike** [comment]
Hi @George-Kihara, thanks for reaching out!

If you can provide us a little more detail we might be able to help.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-auth-library-python/issues

If you are still having issues, please let us know the following details:

#### Environment details

  - OS:
  - Python version:
  - pip version:
  - `google-auth` version:

#### Steps to reproduce (include snippets of the code you are running)

  1. ?
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by George-Kihara** [comment]
Hi @danoscarmike.

Environment:
Os : MacOs
Python version: 3.8.2
pip version: 19.2.3
google-auth version: 1.30.0

Here's the code i'm running:
```
from google.oauth2 import service_account
from google.auth.transport.requests import AuthorizedSession
import json

# Specify the required scope
scopes = [
  "https://www.googleapis.com/auth/firebase"
]

# Authenticate a credential with the service account
credentials = service_account.Credentials.from_service_account_file(
    "mtek-9fb22-firebase-adminsdk-bggqf-96cb9n41r1.json", scopes=scopes)

# Use the credentials object to authenticate a Requests session.
authed_session = AuthorizedSession(credentials)
response = authed_session.get(
    "https://firebasedynamiclinks.googleapis.com/v1/https%3A%2F%2Fmtek.page.link%2FmuUh/linkStats?durationDays=7")

print (response)
```

I keep getting this error:
```
<Response [403]>
```

**Comment by danoscarmike** [comment]
Take a look at https://github.com/googleapis/google-api-dotnet-client/issues/1448. Could be you need to set a specific IAM role on your service account.

**Comment by westarle** [comment]
Please reopen if you are still having trouble.
