### ISSUE TITLE
ADC can load a json of impersonated service account credentials generated by gcloud

### ISSUE THREAD

**Issue by liuchaoren** [googleapis/google-auth-library-python#762]
google-auth-library-java supported ADC impersonation and it is proposed in aip-dev/google.aip.dev#728.

**Comment by liuchaoren** [comment]
@MadJlzz sorry for the late response! Yes, please see https://github.com/googleapis/google-auth-library-python/blob/main/CONTRIBUTING.rst for how to contribute to the repo.

**Comment by DBCerigo** [comment]
Is not supporting `impersonated_service_account` a regression? I'm quite sure that we were using service account impersonation with python clients back in August 2020 (ref: https://stackoverflow.com/questions/69412702/how-to-manage-google-cloud-credentials-for-local-development/69417606)

**Comment by MadJlzz** [comment]
@DBCerigo What I am sure is that you can use it directly from the code (like in my SO thread) but not from the default ADC

**Comment by MadJlzz** [comment]
I made a PR with a first implementation that works where we can discuss around.

**Comment by sloev** [comment]
thanks for doing some work on this @MadJlzz 
coming from AWS, (which has STS for temporary credentials), i must say google is quite inferior on this point.
Its a necessity to be able to run my code locally as a service account in order to develop the strict and narrow permissions my program needs once deployed.

the `gcloud auth application-default login --impersonate-service-account=[SA EMAIL]` is painful (too much friction when context switching between local projects) but it is utterly useless when pythons cloud sdk can't recognize the credentials produced.

crossing my fingers for this to be fixed soon :-)

**Comment by MadJlzz** [comment]
Hey @sloev, thanks for your message. I was out from some time and was stuck with the environment I was working (Windows)
Wasn't able to run all unit tests because spme are using `os` and not `pathlib` if I remind correctly. I will try to move forward on this issue to have a fix asap.

**Comment by liuchaoren** [comment]
Hi @MadJlzz we noticed some some issues which are blocked by this one. Do you think it is possible to fix this issue in one week. I am happy to take it over if it is not feasible. Thanks!

**Comment by MadJlzz** [comment]
Hi @liuchaoren. I don't think I have experience enough with the way your testing this project finish this in one week. Also the PR is waiting your review for the next milestone I have to achieve (which should be covering the new section of the code)
Happy to let you finish if you guys need to be quick on this one.

**Comment by liuchaoren** [comment]
@MadJlzz Thank you for your contribution! I am happy to pick it up from what you have. I will send a PR on the coming Monday.

**Comment by liuchaoren** [comment]
It seems that the scopes are not passed successfully to the impersonated credentials by the default() function. I think we should change the impersonated credentials to inherit the Scoped base class so that the default() can add scopes correctly to it. I will reopen it and will follow up with a PR to fix it.
