### ISSUE TITLE
google.auth.default(quota_project_id="..") still results in end user credentials warning

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-auth-library-python#769]
`quota_project_id` is not currently passed through to `_get_gcloud_sdk_credentials`. This bit of code still results in the end user credentials warning:

```py
import google.auth

credentials, project_id = google.auth.default(quota_project_id="my-project")
```

https://github.com/googleapis/google-auth-library-python/blob/09e0389db72cc9d6c5dde34864cb54d717dc0b92/google/auth/_default.py#L177-L195

https://github.com/googleapis/google-auth-library-python/blob/09e0389db72cc9d6c5dde34864cb54d717dc0b92/google/auth/_default.py#L73-L75

**Comment by busunkim96** [comment]
Hey @arithmetic1728,

Re-visiting this as it recently went OOSLO. Should a quota project passed explicitly to `google.auth.default(quota_project_id="my-project")` silence the warning? Or should the project be explicitly added through `gcloud`?

https://github.com/googleapis/google-auth-library-python/blob/09e0389db72cc9d6c5dde34864cb54d717dc0b92/google/auth/_default.py#L50-L70

**Comment by arithmetic1728** [comment]
@busunkim96 yes, we should silence the error if the quota project id is provided via `google.auth.default(quota_project_id="my-project")`. I will write a PR to address it.
