### ISSUE TITLE
AttributeError: module 'grpc' has no attribute 'AuthMetadataPlugin'

### ISSUE THREAD

**Issue by Edvard-D** [googleapis/google-auth-library-python#791]
#### Environment details

  - OS: Ubuntu 20.04
  - Python version: 3.8.5
  - pip version: 20.0.2
  - `google-auth` version: 1.32.0

#### Steps to reproduce

1. Download Google Research's [SEED Reinforcement Learning codebase](https://github.com/google-research/seed_rl).
2. Modify the code so that it installs the google-cloud-storage package and imports the google.cloud.storage module at some point after the seed_rl/gcp/run.py file is run.
3. Initialize a Google AI Platform training session by running the .sh file under seed_rl/gcp that corresponds to the environment you modified to import google.cloud.storage.
4. This will produce the following error, visible through the Google Cloud Logs Explorer interface:

    Traceback (most recent call last):
    File "gcp/run.py", line 23, in <module>
    from seed_rl.trader import vtrace_main
    File "/seed_rl/trader/vtrace_main.py", line 24, in <module>
    from seed_rl.trader import batched_environment_settings
    File "/seed_rl/trader/batched_environment_settings.py", line 2, in <module>
    import google.cloud.storage as storage
    File "/usr/local/lib/python3.6/dist-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
    File "/usr/local/lib/python3.6/dist-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
    File "/usr/local/lib/python3.6/dist-packages/google/cloud/_helpers.py", line 38, in <module>
    import google.auth.transport.grpc
    File "/usr/local/lib/python3.6/dist-packages/google/auth/transport/grpc.py", line 43, in <module>
    class AuthMetadataPlugin(grpc.AuthMetadataPlugin):
    AttributeError: module 'grpc' has no attribute 'AuthMetadataPlugin'

As a note, the SEED codebase packages the code as a Docker image and uploads it to Google Cloud. That image is used by AI Platform to execute training. I have not installed the google-auth package directly; the version that's used is the one that was installed as part of the google-cloud-storage installation process.

**Comment by busunkim96** [comment]
Hi,

It looks like `grpc` is getting successfully imported by `google-cloud-core` (see [code](https://github.com/googleapis/python-cloud-core/blob/6399b8007632088cd60dd77e24ab46850ad958cc/google/cloud/_helpers.py#L36-L40)) but that something goes wrong after that point. `AuthMetadataPlugin` is not a new addition to the `grpcio` package so I don't think it's a version issue.

Could you go into more detail into how `google-cloud-storage` is installed? Are any other packages installed next to it?

**Comment by Edvard-D** [comment]
Thanks for the reply. google-cloud-storage is installed as follows in a Dockerfile: `RUN pip3 install google-cloud-storage`. It's installed alongside the following packages:
- gym
- aiohttp
- dataclasses
- google-cloud-logging
- tensorflow (v 2.4.1-gpu)
- tensorflow-probability (v 0.11.0)

An example of how the Dockerfile is setup can be found [here](https://github.com/google-research/seed_rl/blob/master/docker/Dockerfile.football). These packages are installed toward the bottom after `WORKDIR /`. Unfortunately there's no other output available to help identify where things are going wrong.

**Comment by busunkim96** [comment]
I wonder if `grpcio` is getting installed a bit differently through `tensorflow`, and the import is getting messed up as a result. 🤔  
- Could you do a `pip freeze` at the end of the Dockerfile (if it's possible to see the logs from the container getting built)?
- Could you try adding `grpcio` to the list of packages that are explicitly installed?

**Comment by Edvard-D** [comment]
Using `pip freeze` I found that `grpcio==1.32.0` was installed. On my system after installing `google-cloud-storage` it had `grpcio==1.34.0`. I tried installing that version explicitly but it produced the same result.

Your comment reminded me that the SEED project actually uses what I believe is a [modified version of gRPC](https://github.com/google-research/seed_rl/tree/master/grpc). This must be the root of the problem, right? Not sure what the work around would be, though.

**Comment by busunkim96** [comment]
Hmm that might be it.

Would you mind sharing `.sh` and `.py` files to create a basic repro? I don't have quite enough context on AI Platform and this repo to know where I should be making the changes.

**Comment by Edvard-D** [comment]
My dev machine (VM in Google Cloud) got flagged for crypto mining for some reason, so I need to get that sorted before I use that machine again to make sure it doesn't happen again. Because of this I can't verify this myself, but I believe these changes should trigger the same error:

1. Download seed_rl source code on an Ubuntu/Windows system that has Docker installed.
2. Modify `seed_rl/football/vtrace_main.py` to import google.cloud.storage.
3. Modify `seed_rl/docker/Dockerfile.football` to install `google-cloud-storage` using pip.
4. Run `seed_rl/gcp/train_football_checkpoints.sh` to build, upload, and start training on AI Platform. From my understanding, you can also run `seed_rl/docker/run.sh` to have it run on your local machine instead. Haven't tried it myself so I can't be sure that it'll produce the same error, though if it doesn't I guess that tells us something, too.
5. If you run this on AI Platform, go to AI Platform > Jobs to see the job that's been created. It will take around ten minutes to get set up, run, and error out. Once it does there will be a red symbol next to the job name indicating that it failed. Look to the far right of the name and there will be a link to view the logs of the training session.

Once I can safely access that machine again I can give it a shot too to verify this produces the error as well, but you may be able to try it out before I'm able to. If any questions about the SEED code comes up I can try to answer those, too.

**Comment by Edvard-D** [comment]
This ended up being a problem with some changes I made to the SEED codebase that I had made to work around a different bug. I figured out the correct way to fix the original problem, allowing me to use the methodology the SEED programmers used. That resolved this error for me.
