### ISSUE TITLE
service account authentication fails after 1.33.0 release 

### ISSUE THREAD

**Issue by syphar** [googleapis/google-auth-library-python#804]
#### Environment details

  - OS: Linux
  - Python version: 3.9.6
  - pip version: 21.1.3
  - `google-auth` version: 1.33.0

#### Error description 

With the update of google-auth to 1.33.0 we saw an error in our environments. 

> invalid_grant: Invalid JWT: Failed audience check. The right audience is [...] 

In our case we use a service-account to access google calendars in our org. 

In our service-account key we find `"token_uri": "https://accounts.google.com/o/oauth2/token"`, while the library sets [`aud` to be `https://oauth2.googleapis.com/token` via a constant](https://github.com/googleapis/google-auth-library-python/blob/306115d9dcf0b1806630563ae2d0aa40866966fb/google/oauth2/service_account.py#L386). This was changed with the 1.33.0 release in 0e264092e35ac02ad68d5d91424ecba5397daa41. 

When I monkey-patch the constant to have the same value as the token-uri in our accounts, everything works again. 

Is this a bug? Or a configuration issue on our side? 

I'm happy to provide detailed steps to reproduce this if needed. Also I'm not sure about the relation to #464.

**Comment by busunkim96** [comment]
Thanks for the report! @arithmetic1728 Could you take a look? 

I think `https://oauth2.googleapis.com/token` is the current `token_endpoint` (see https://developers.google.com/identity/protocols/oauth2/openid-connect#discovery). Do older keys use different endpoints?

**Comment by busunkim96** [comment]
Hi,

If you're experiencing this issue, please use the prior release `google-auth==1.32.1`. We are working at solutions in the backend.

**Comment by syphar** [comment]
> Hi,
> 
> If you're experiencing this issue, please use the prior release `google-auth==1.32.1`. We are working at solutions in the backend.

Thank you for the update! We already had reverted the upgrade, will wait for the next release and the fix.

**Comment by Mogost** [comment]
We also investigated the issue on our side. In our case, changing the `token_uri` value in the `.json` file helped us.

**Comment by syphar** [comment]
> We also investigated the issue on our side. In our case, changing the `token_uri` value in the `.json` file helped us.

thanks, that's good to know. I would have expected the token to be signed, so that it fails when these details are changed, that's why I didn't try to change it. 

Since there is no rush upgrading the package, we'll just wait for the fix and release

**Comment by liuchaoren** [comment]
I can reproduce the error only when I set the "subject" filed for domain-wide delegation. Can anyone confirm if domain-wide delegation is used when you see the error?

**Comment by syphar** [comment]
> I can reproduce the error only when I set the "subject" filed for domain-wide delegation. Can anyone confirm if domain-wide delegation is used when you see the error?

Yep, in our case the service account has domain wide delegation activated

**Comment by busunkim96** [comment]
Revert is under way in https://github.com/googleapis/google-auth-library-python/pull/808, we'll take the change again once b/194191737 is resolved.

**Comment by syphar** [comment]
just tested the revert with 1.33.1, and it works (which I assumed seeing the code, but still :) )

Thank you for the quick fix!
