### ISSUE TITLE
Add 'docfx' session, wire into Kokoro 'docs-presubmit' job.

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-auth-library-python#822]
While working on PR #799 (to fix #797), I discovered that there is no `docfx` session in `noxfile.py`.

I made a quick effort to copy one in, but ran into issues which seemed harder than needed to get the CI job passing, so I'm opening this issue to track.

- [ ] Copy in a `docfx` session from another repo.
- [ ] Normalize `docs/config.py` with other repo to get required changes (path setup, etc.)
- [ ] Get `docs` session building with the same version of Sphinx.
- [ ] Re-add `docfx` to the `.kokoro/docs/docs-presubmit.cfg` configuration.

**Comment by dandhlee** [comment]
docfx sessions are currently only required for Google Cloud client library. While I think it's fine to leave this open for in the future when docfx expands to non-Cloud libraries as well, don't sweat on having this done anytime soon!

**Comment by parthea** [comment]
Closing as obsolete
