### ISSUE TITLE
chore: references to "oauth2client" master branch

### ISSUE THREAD

**Issue by nicain** [googleapis/google-auth-library-python#853]
During the master --> main migration, I noticed references that point to the master branch of https://github.com/googleapis/oauth2client

After that repo is migrated, we will need to circle back to this repo (and potentially others) and fix these references

- [ ] CHANGELOG.md

xref: googleapis/google-cloud-python#10579

**Comment by JustinBeckwith** [comment]
Yeah no reason to go messing with archived repos. Please leave that as is.
