### ISSUE TITLE
create key for service account

### ISSUE THREAD

**Issue by cometta** [googleapis/google-auth-library-python#893]
``` service.projects().serviceAccounts().keys().create(..) ``` . Is there anyway to specify the expiry date for the key? does this able to output a json file?

**Comment by cometta** [comment]
Hello @arithmetic1728 the module i plan to use is "from google.oauth2 import service_account" , i got info from this guide 
https://cloud.google.com/iam/docs/creating-managing-service-account-keys#iam-service-account-keys-create-python

**Comment by arithmetic1728** [comment]
@cometta `service.projects().serviceAccounts().keys().create(..)` is the `iam` API call to create service account keys, it comes from the `googleapiclient.discovery` module, not `google.oauth2` module. Let me rewrite the sample so it can be clear to you what each module does.

```
import os

def create_credentials():
    """Create a credential which has permission to call IAM API"""
    from google.oauth2 import service_account

    credentials = service_account.Credentials.from_service_account_file(
        filename=os.environ['GOOGLE_APPLICATION_CREDENTIALS'],
        scopes=['https://www.googleapis.com/auth/cloud-platform'])
    return credentials

def create_key(service_account_email):
    # Create a credential which has permission to call IAM service account API.
    credentials = create_credentials()

    # Call IAM service account API to create key.
    service = googleapiclient.discovery.build(
        'iam', 'v1', credentials=credentials)
    key = service.projects().serviceAccounts().keys().create(
        name='projects/-/serviceAccounts/' + service_account_email, body={}
        ).execute()

    print('Created key: ' + key['name'])
``` 

I am not familiar with IAM API, but you can check the following link to see more details on how to use this API: https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts.keys

**Comment by cometta** [comment]
thank you for clarrification
