### ISSUE TITLE
_helpers.utcnow() return not timezone aware

### ISSUE THREAD

**Issue by steven-cutting** [googleapis/google-auth-library-python#977]
https://github.com/googleapis/google-auth-library-python/blob/c6e72871e0ed15693aee903d56a3fb1b72f4b87f/google/auth/_helpers.py#L69

Is there a reason why `_helpers.utcnow()` does not return a timezone aware datetime object?

From the users perspective, without diving into the code, it's not clear on upstream objects (e.g. `Credentials.expiry`) if a datetime is local or utc.

**Comment by arithmetic1728** [comment]
This library only uses UTC for the datetime.
