### ISSUE TITLE
Update automatic retries and Implement Retryable interface for token endpoint requests

### ISSUE THREAD

**Issue by TimurSadykov** [googleapis/google-auth-library-python#980]
Current implementation of automatic retries to token endpoint does not follow Auth service guidelines. In addition, clients do not have a good way to distinguish retryable errors and implement custom retry strategies. Sometimes this causes infinite retries like here: https://github.com/nwbirnie/gapic-oauth-invalid-hangs

More details in the doc: go/auth-correct-retry

Please prioritize the fix if infinite retry like for Java is repro here as well.

**Comment by arithmetic1728** [comment]
assigning to Timur to prioritize the work

**Comment by clundin25** [comment]
https://github.com/googleapis/google-auth-library-python/pull/1113
