### ISSUE TITLE
Please remove this library's dependency on the gcloud command line tool

### ISSUE THREAD

**Issue by atrigent** [googleapis/google-auth-library-python#981]
https://github.com/googleapis/google-auth-library-python/blob/fffe3d01c4b397603639322bbd0ba062c03dacb7/google/auth/_cloud_sdk.py#L34-L40

What exactly is the point of having a library if you're just going to resort to running a command-line tool in a subprocess whenever it suits you?

**Comment by arithmetic1728** [comment]
`_CLOUD_SDK_CONFIG_COMMAND` is used to get the project id stored by gcloud if gcloud is installed. It's fine if gcloud is not installed, the project id is `None` in that case.

`_CLOUD_SDK_USER_ACCESS_TOKEN_COMMAND` is an easy way to allow users to use the access token stored in gcloud. It is only used when user use `UserAccessTokenCredentials`.
