### ISSUE TITLE
Fails to detect service account from cloud run with auth.default()

### ISSUE THREAD

**Issue by aebrahim** [googleapis/google-auth-library-python#998]
`creds, _ = google.auth.default(); print(creds.service_account_email)` yields `default`

#### Environment details

  - OS: python:3.10-slim dockerfile (Debian GNU/Linux 11 (bullseye))
  - Python version: 3.10.4
  - pip version: 22.0.4
  - `google-auth` version: 2.6.2

#### Steps to reproduce

  1. Modify the helloworld cloudrun [example](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/run/helloworld/main.py), as show below, or do `git clone https://github.com/aebrahim/python-docs-samples.git -b auth_bug_demo --depth 1 && cd run/helloworld/ ` to get an already working example.
  ```python
  @app.route("/")
  def hello_world():
    name = os.environ.get("NAME", "World")
    creds, project_id = google.auth.default()
    from_name = creds.service_account_email
    return f"Hello {name} from {from_name}!"
  ```
  2. `export GOOGLE_CLOUD_PROJECT=my-project`
  3. `gcloud builds submit --tag gcr.io/${GOOGLE_CLOUD_PROJECT}/helloworld`
  4. `gcloud run deploy helloworld --allow-unauthenticated --image gcr.io/${GOOGLE_CLOUD_PROJECT}/helloworld`  -> gives "Hello World from default!"
  5. `gcloud run deploy helloworld --allow-unauthenticated --image gcr.io/${GOOGLE_CLOUD_PROJECT}/helloworld --service-account=test-app-deploy@${GOOGLE_CLOUD_PROJECT}.iam.gserviceaccount.com`  -> gives "Hello World from default!"

**Comment by arithmetic1728** [comment]
You need to call the refresh method (which calls the metadata server to retrieve the service account email), something like the following

```
import google.auth.transport.requests

creds, project_id = google.auth.default()

req = google.auth.transport.requests.Request()
creds.refresh(req)

from_name = creds.service_account_email
```

**Comment by arithmetic1728** [comment]
please reopen the issue if the solution doesn't work, thanks, closing it for now
