### ISSUE TITLE
facing issues while generating new access token using refresh token

### ISSUE THREAD

**Issue by mist3rGP** [googleapis/google-auth-library-python#999]
#### Environment details

  - OS: Win 10
  - Python version:
  - pip version:
  - `google-auth` version: 2.6.2

#### Steps to reproduce

  1. Generate access token and refresh token. Wait for token to expire. Have logic to check validity of token. Refresh token with refresh token
  2. It will throw this error: "google.auth.exceptions.RefreshError: ('invalid_scope: Some requested scopes were invalid. {invalid=[a, c, d, e, g, h, i, l, m, ., /, o, p, r, s, t, u, w, :]}', {'error': 'invalid_scope', 'error_description': 'Some requested scopes were invalid. {invalid=[a, c, d, e, g, h, i, l, m, ., /, o, p, r, s, t, u, w, :]}', 'error_uri': 'https://developers.google.com/identity/protocols/oauth2'})"

Thanks!

**Comment by arithmetic1728** [comment]
could you provide a simple sample to repro?

**Comment by shivansh9007** [comment]
if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)  
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', 'https://www.googleapis.com/auth/spreadsheets') # here enter the name of your downloaded JSON file
            creds = flow.run_local_server(port=0)
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)

    service = build('sheets', 'v4', credentials=creds)
    cred = None
    if os.path.exists('token_write.pickle'):
        with open('token_write.pickle', 'rb') as token:
            cred = pickle.load(token)
    if not cred or not cred.valid:
        if cred and cred.expired and cred.refresh_token:
            cred.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file('credentials.json', 'https://www.googleapis.com/auth/spreadsheets')
            cred = flow.run_local_server()
        with open('token_write.pickle', 'wb') as token:
            pickle.dump(cred, token)



Using this sample code thats present on the samples page for google sheets.
Once the creds expire and we try to generate new token with refresh token the API throws this error.

**Comment by shivansh9007** [comment]
Any Updates??

**Comment by sai-sunder-s** [comment]
The [scopes parameter](https://github.com/googleapis/google-auth-library-python-oauthlib/blob/main/google_auth_oauthlib/flow.py#L348-L350) that is passed to InstalledAppFlow.from_client_secrets_file is a Sequence.
So it should be something like this
```
flow = InstalledAppFlow.from_client_secrets_file(
            'credentials.json', ['https://www.googleapis.com/auth/spreadsheets'])
```

Please feel free to reopen the issue if this doesn't solve your problem.
